### ISSUE TITLE
How do you configure cluster_formation.consul.svc_addr_nic = en0 on Windows

### ISSUE THREAD

**Issue by danassetms** [rabbitmq/discussions#109]
Following the guidance to setup a Consul RabbitMQ cluster I've get everything working except this.  My service registers with the node name which can't then be resolved by anything else using Consul so I need RabbitMQ to register with the IP address of the machine but I can't get this option to work:

cluster_formation.consul.svc_addr_nic = en0

It just causes Rabbit to crash with the following error

2020-06-03 19:36:20.124 [info] <0.345.0> Will register with peer discovery backend rabbit_peer_discovery_consul
2020-06-03 19:36:20.124 [error] <0.344.0> CRASH REPORT Process <0.344.0> with 0 neighbours exited with reason: no match of right hand value {error,not_found} in rabbit_peer_discovery_consul:service_address/4 line 415 in application_master:init/4 line 138
2020-06-03 19:36:20.124 [info] <0.44.0> Application rabbit exited with reason: no match of right hand value {error,not_found} in rabbit_peer_discovery_consul:service_address/4 line 415

**Comment by michaelklishin** [comment]
The function that returns a "not found" result is [this one](https://github.com/rabbitmq/rabbitmq-peer-discovery-common/blob/master/src/rabbit_peer_discovery_util.erl#L155). It inspects all interfaces returned by `inet:getifaddrs/0` when it's looking for a match.

You can invoke that function on Windows in the shell (`erl.exe`):

```
inet:getifaddrs().
```

(the trailing dot is mandatory). The first argument will be the interface name, something like this:

```
     {"en0",
      [{flags,[up,broadcast,running,multicast]},
       {addr,{192,168,1,142}},
       {netmask,{255,255,255,0}},
       {broadaddr,{192,168,1,255}},
       {hwaddr,[140,133,144,25,251,110]}]},
     {"en3",
      [{flags,[up,broadcast,running,multicast]},
       {hwaddr,[130,30,245,203,136,1]}]},
     {"en1",
      [{flags,[up,broadcast,running,multicast]},
       {hwaddr,[130,30,245,203,136,0]}]},
     {"en4",
      [{flags,[up,broadcast,running,multicast]},
       {hwaddr,[130,30,245,203,136,5]}]},
     {"en2",
      [{flags,[up,broadcast,running,multicast]},
       {hwaddr,[130,30,245,203,136,4]}]},
```

I'd recommend against using NIC-derived service name as IP addresses change. Using hostnames on each machine that resolves for all peers is a better, more forward-compatible option.

**Comment by michaelklishin** [comment]
Apparently there is a function that lists interface names only: `inet:getiflist/0`, so

``` erl
inet:getiflist().
```

in the shell would be an easier option.
