### ISSUE TITLE
 Connection attempt from node rabbit@fbd0bef31d61 rejected. Invalid challenge reply.

### ISSUE THREAD

**Issue by Fossil01** [rabbitmq/discussions#113]
Trying to setup a cluster with Docker Swarm and etcd as the autodiscovery backend. I get this error on startup, can't find anything using Google that applies.

Is there any information about this?

rabbitmq.conf:

```
loopback_users.guest = false
listeners.tcp.default = 5672
default_pass = test123
default_user = test
management.tcp.port = 15672

cluster_formation.peer_discovery_backend = rabbit_peer_discovery_etcd
cluster_formation.etcd.cluster_name = production

cluster_formation.etcd.endpoints.1 = 10.100.20.19:2379
cluster_formation.etcd.endpoints.2 = 10.100.20.20:2379
cluster_formation.etcd.endpoints.3 = 10.100.20.21:2379

# Forcefully remove unknown nodes from the cluster
cluster_formation.node_cleanup.only_log_warning = false

log.file.level = debug
log.console.level = debug
```

```
 etcdctl get --prefix=true "/"
/rabbitmq/discovery/rabbitmq/clusters/production/nodes/rabbit@65bfc680e0da
{"lease_id":2029560603933801994,"node":"rabbit@65bfc680e0da","ttl":61}
/rabbitmq/discovery/rabbitmq/clusters/production/nodes/rabbit@8d6984ed9f37
{"lease_id":2383093174648781414,"node":"rabbit@8d6984ed9f37","ttl":61}
/rabbitmq/discovery/rabbitmq/clusters/production/nodes/rabbit@fbd0bef31d61
{"lease_id":2383093174648781420,"node":"rabbit@fbd0bef31d61","ttl":61}
```

**Comment by michaelklishin** [comment]
There are several things that may be going on but you haven't provided any logs, and logs is a **critically important** source of information. If you are looking for free support from the core team, consider helping us help you by always sharing logs.

We do not know what RabbitMQ version is used. For example, `3.8.4` requires etcd 3.4 and also has an unfortunate bug that [has already been addressed](https://github.com/rabbitmq/rabbitmq-peer-discovery-etcd/issues/28). Older versions use a different major etcd API version. So we have to guess what may be going on and **guessing is very time inefficient** for everyone involved.

"Invalid challenge reply" suggests your nodes may be using a different Erlang cookie. Specifically this line

```
# Forcefully remove unknown nodes from the cluster
cluster_formation.node_cleanup.only_log_warning = false
```

is very dangerous. One consequence of [forced node removal](https://www.rabbitmq.com/cluster-formation.html#node-health-checks-and-cleanup) is that a removed node can come back and attempt to rejoin its existing cluster but peers will **refuse to accept it** since they do not believe that the node is a cluster member. This is documented in [Nodes Rejoining Their Existing Cluster](https://www.rabbitmq.com/cluster-formation.html#rejoining). Consider against using that setting.

However, "invalid challenge" more likely indicates a blank node which was re-created with a different Erlang cookie. It won't be able to [authenticate to the rest of the cluster](https://www.rabbitmq.com/clustering.html#erlang-cookie).

**Comment by Fossil01** [comment]
Hi,

Didn't post the logs because I did not see anything related in there but I could be blind ofc :-) I am using 3.8-rc-management as the Docker image. etcd is version 3.4.9.

Thanks for the cookie tip. I was Googling for "challenge" and nothing came up :-) I have set that now and it works!

**Comment by michaelklishin** [comment]
Indeed I can reproduce

```
2020-06-15 13:01:59.101 [error] <0.1076.0> ** Connection attempt from node 'rabbitmqcli-99004-rabbit@warp10' rejected. Invalid challenge reply. **
```

by providing a mismatching Erlang cookie to CLI tools:

```
rabbitmq-diagnostics --erlang-cookie "will-fail-to-authenticate-123" status
```

while tailing target node logs with

```
rabbitmq-diagnostics log_tail_stream
```

So a node has received a CLI tool or peer node connection request that used an incorrect shared secret (Erlang cookie) and was rejected.

```
cluster_formation.node_cleanup.only_log_warning = false
```

which forcefully removes cluster nodes can lead to similar issues (covered in [Node Rejoining Their Existing Cluster](https://www.rabbitmq.com/cluster-formation.html#rejoining)) but not specifically this one. My best guess is that something happens to newly started pods/Swarm nodes in your environment, e.g. they get a new cookie generated for them.

**Comment by Fossil01** [comment]
I am now setting the cookie in my compose file, works perfectly.

**Comment by michaelklishin** [comment]
I am reminded that that CLI tools use node names that begin with `rabbitmqctl-*` (a "feature" I introduced for simplified troubleshooting in 2017 and have since forgotten about 😅) so it was a RabbitMQ node connection.

**Comment by Fossil01** [comment]
By the way. I think I need: `cluster_formation.node_cleanup.only_log_warning = false` in my case because when Docker Swarm rebalances things it leaves old/removed containers behind as nodes in etcd.

**Comment by michaelklishin** [comment]
@Fossil01 cool, so you didn't have a fixed cookie set in the Docker compose file and the node generated a random one on first boot? That sounds plausible. We should somehow mention this in the docs.

**Comment by Fossil01** [comment]
Exactly. I was being dumb :-)

**Comment by michaelklishin** [comment]
I understand that

```
cluster_formation.node_cleanup.only_log_warning = false
```

is the behavior some users want. But it often comes with unintended side effects, so I always recommend against it at first.

Specifically in etcd's peer discovery case, node keys use a lease that they renew. Eventually this lease will expire and the key will be deleted/compacted by etcd itself. You can use a lower value by setting `cluster_formation.etcd.node_ttl` . The default is [61 seconds](https://github.com/rabbitmq/rabbitmq-peer-discovery-etcd/blob/master/src/rabbitmq_peer_discovery_etcd_v3_client.erl#L43).

**Comment by Fossil01** [comment]
So the old nodes should be removed from the cluster after 61 secs? I think I let it run longer than that and they were still there, but will test again.

**Comment by michaelklishin** [comment]
It's an easy mistake to make. Until we produce a dedicated Kubernetes guide (Docker Swarm is not Kubernetes but many problems and solutions are more or less identical), there is no obvious place to document such things. I'll try to expand the Erlang cookie section. Thanks for confirming my hypothesis.

**Comment by michaelklishin** [comment]
Node TTL controls the key life span in etcd.

The plugin will remove a node if `cluster_formation.node_cleanup.only_log_warning` is set to `false` and a cluster member is not found in peer discovery results.

**Comment by michaelklishin** [comment]
Enabling debug logging will log node removal decisions such as

> Peer discovery: checking for partitioned nodes to clean up

> Peer discovery: cleanup discovered unreachable nodes: …

> Peer discovery: checking for partitioned nodes to clean up

**Comment by michaelklishin** [comment]
Actually I was wrong. The modules that performs the cleanup is [this one]() and it does two things:

 * Periodically runs (the interval is controlled via [`cluster_formation.node_cleanup.interval`](https://github.com/rabbitmq/rabbitmq-peer-discovery-common/blob/master/priv/schema/rabbitmq_peer_discovery_common.schema#L3)), the default is 60 seconds
 * Either logs or permanently removes unreachable (down) cluster members (the same way `rabbitmqctl forget_cluster_node` does)

And the etcd key lease controls if such nodes can be discovered by newly joining peers. If a node truly is down, there is no harm in discovering it as it will be skipped after an unsuccessful connection.

**Comment by michaelklishin** [comment]
Ugh, and `cluster_formation.node_cleanup.interval` is not documented 🤦

**Comment by Fossil01** [comment]
Haha. Well at least this is all discoverable by Google now :P

**Comment by michaelklishin** [comment]
Pushed some doc guide updates, they will be live later today.
