### ISSUE TITLE
Unable to disable metrics aggregation through configuration

### ISSUE THREAD

**Issue by lechen26** [rabbitmq/discussions#115]
Hi

i have a RabbitMQ deployment on K8s which includes configmap that includes all configuration and enabled plugins. which one of them is rabbitmq_prometheus

the image i'm using is: rabbitmq:3.8.2

i'm trying to set:
` prometheus.return_per_object_metrics = true`

and get the following error:

> 18:47:07.183 [error] You've tried to set prometheus.return_per_object_metrics, but there is no setting with that name.
> 18:47:07.183 [error]   Did you mean one of these?
> 18:47:07.257 [error]     prometheus.ssl.honor_ecc_order
> 18:47:07.257 [error]     prometheus.ssl.reuse_sessions
> 18:47:07.257 [error]     prometheus.tcp.compress

i thougth at first that maybe the plugin wasnt anable first, but i do able to configure other property such as:
`prometheus.tcp.port =  15692`

i do able to enable it at runtime using:
`rabbitmqctl eval 'application:set_env(rabbitmq_prometheus, return_per_object_metrics, true).'`

what am i missing?
thanks

**Comment by michaelklishin** [comment]
Prior to `3.8.3`, the plugin always serves per-object metrics. If that's what you want, there is nothing to configure.

**Comment by lechen26** [comment]
wow sorry, i've must have played with few versions, and missed that.
10x!
