### ISSUE TITLE
Can the latest 3.8 version of rabbitmq management view the detailed message information of the delay queue?

### ISSUE THREAD

**Issue by 501956430** [rabbitmq/discussions#116]
Can the latest 3.8 version of rabbitmq management view the detailed message information of the delay queue, such as: message details, expiration time, etc. do you know whether this requirement has been solved?

**Comment by michaelklishin** [comment]
Nothing has changed in 3.8. There are some plans to develop a new delayed message exchange plugin (no ETA) but not a message browsing feature.
