### ISSUE TITLE
queue metrics on mirrored queues

### ISSUE THREAD

**Issue by lechen26** [rabbitmq/discussions#117]
Hi

i have a cluster of RabbitMQ with 2 nodes with a mirror between them on all queues. (ha-all).
i've used to use the prometheus_rabbitmq_exporter and was able to see metrics from both nodes with pretty much the same values, for example rabbitmq_queue_messages on specific queue from node1 and node2 usually had the same value, or at least close.

i've switched now to use the built it rabbitmq_prometheus (in version 3.8.2), and seems like although the queues are mirrored the same, i only see metrics from the master node.
when executing query on prometheus for queue_messages_ready i only see data from master node.
here is the graph, for queue_messages_ready on specific queue, you can see once i've switched the master node , the data starting to arrives from his exporter.
![image](https://user-images.githubusercontent.com/7347506/84863354-79dabb80-b07d-11ea-8dd0-1a2905082b38.png)

how can i resolved this?
10x

**Comment by michaelklishin** [comment]
Only the primary queue replica collects metrics. Mirrors are not particularly interesting and we see no reason to split off their metrics as it can be very misleading.

In other news, [two node clusters](https://www.rabbitmq.com/clustering.html#node-count) are explicitly recommended against, and so is ["ha-all"](https://www.rabbitmq.com/ha.html#replication-factor).

**Comment by michaelklishin** [comment]
It's worth mentioning that individual queue metrics is an option [only for some environments](https://www.rabbitmq.com/prometheus.html#metric-aggregation) and separating mirror metrics, even if there was any practical reason to do so, would only make the need for aggregation worse (consider the case in rabbitmq/rabbitmq-prometheus#24. In the case of aggregation, such separation would make even less sense.

For quorum queues, there is a Raft backlog metric that allows you to see how far behind a certain replica is.
