### ISSUE TITLE
Can you provide Jest Unit Test Example for any rabbitMQ Publish

### ISSUE THREAD

**Issue by Rajanusa** [rabbitmq/discussions#12]
Hi,

I used all the rabbit MQ javascript file given here in my nodejs typescript project.
Can you help me on Unit Test, How to mock and handle chain of promises in any of your example give here.
https://github.com/rabbitmq/rabbitmq-tutorials/tree/master/javascript-nodejs/src

Thanks
Raj

**Comment by michaelklishin** [comment]
I'm afraid our team are not JavaScript testing experts. The client in question is used in our tutorials but is community-maintained. You can take a look at the client's own test suite and test suites of other clients, although most of them do not use futures, promises or similar constructs, and mocking is used very sparingly or not at all.

Most consumer functions or objects can be tested in isolation. I'd recommend using integration tests for other messaging-related parts.
