### ISSUE TITLE
Messages out of order when redelivered and consumed with a global prefetch

### ISSUE THREAD

**Issue by sdurrenmatt** [rabbitmq/discussions#120]
Hi,

I am implementing a queue consumer respecting the following principles:

- Messages must be consumed one by one and in order
- If a message cannot be processed, it is rejected and must be requeued at the same position
- After reaching a certain number of redeliveries, it is rejected without being requeued

In order to achieve this:
- SAC is enabled on the queue, so there can be only one consumer at the same time
- Acknowledgement is manual and prefetch is set to 1, so there can be only one message consumed and processed at the same time
- Since redelivery limit is not a classic queue feature, a redelivery count is maintained to check whether the current message must be requeued or not

Using a local consumer prefetch, everything works properly. However if the prefetch is global, messages are randomly out of order when redelivered and consumed. Is there something I am missing about RabbitMQ channel prefetch mechanism? 

Here are my JUnit tests (one with "local" prefetch and the other with "global" prefetch):

```java
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import com.rabbitmq.client.Channel;
import com.rabbitmq.client.Connection;
import com.rabbitmq.client.ConnectionFactory;
import com.rabbitmq.client.DeliverCallback;

public class RedeliveryOrderWithQosTest {

    private static final String QUEUE_TEST = "redelivery-order-with-qos-test";

    private static final Integer NB_MESSAGES = 100;

    private Channel channel;

    private static CountDownLatch lock;

    private static Integer redeliveryCount;

    private static Integer messageCount;

    private boolean isOrdered;

    @BeforeEach
    public void setUp() throws Exception {
        // Before each test, create a new connection
        final ConnectionFactory connectionFactory = new ConnectionFactory();
        connectionFactory.setHost("localhost");
        connectionFactory.setPort(5672);
        connectionFactory.setUsername("guest");
        connectionFactory.setPassword("guest");
        connectionFactory.setVirtualHost("/");
        connectionFactory.setAutomaticRecoveryEnabled(true);
        final Connection connection = connectionFactory.newConnection();

        // Create a new channel and queue
        channel = connection.createChannel();
        channel.queueDeclare(QUEUE_TEST, true, false, true, null);

        // Fill the queue with some messages
        for (int i = 0; i < NB_MESSAGES; ++i) {
            channel.basicPublish("", QUEUE_TEST, false, null, String.valueOf(i).getBytes());
        }
    }

    @BeforeEach
    private void initCounts() {
        lock = new CountDownLatch(NB_MESSAGES);
        messageCount = 0;
        redeliveryCount = 0;
    }

    private void consumeWithRedeliveryAndCheckOrder() throws Exception {
        isOrdered = true;

        final DeliverCallback deliverCallback = (consumerTag, delivery) -> {
            // check that message order is preserved			
            final String message = new String(delivery.getBody());
            System.out.println("Consuming message " + message);
            isOrdered &= Integer.valueOf(message).equals(messageCount);

            final long deliveryTag = delivery.getEnvelope().getDeliveryTag();
            if (redeliveryCount < 10) {
                // redeliver message 10 times
                channel.basicReject(deliveryTag, true);
                ++redeliveryCount;
            } else {
                // reject message and consume next message
                channel.basicReject(deliveryTag, false);
                redeliveryCount = 0;
                ++messageCount;
                lock.countDown();
            }
        };

        channel.basicConsume(QUEUE_TEST, false, deliverCallback, consumerTag -> {});
        lock.await(10000, TimeUnit.MILLISECONDS);
    }

    @Test
    public void testRedeliveryOrderWithLocalPrefetch() throws Exception {
        channel.basicQos(1, false);
        consumeWithRedeliveryAndCheckOrder();
        assertTrue(isOrdered);
    }

    @Test
    public void testRedeliveryOrderWithGlobalPrefetch() throws Exception {
        channel.basicQos(1, true);
        consumeWithRedeliveryAndCheckOrder();
        assertTrue(isOrdered);
    }

}
```

Versions used are RabbitMQ 3.8.3 / Erlang 22.2.6 / RabbitMQ Java Client 5.9.0

**Comment by michaelklishin** [comment]
Global prefetch [has a different meaning in RabbitMQ](https://www.rabbitmq.com/consumer-prefetch.html) compared to the semantics of the AMQP 0-9-1 spec. When you set the prefetch relative to consumer registration indeed is going to have an effect in a test that expects a single "in-flight" delivery.

**Comment by sdurrenmatt** [comment]
Hello Michael,

Thank you for your time. I will try to take a traffic capture to make sure
of what happens. What I do not understand is how there can be parallel
processing of deliveries (with manual ack and prefetch of 1), and how there
can be concurrent events on the queue. Do you mean that message requeuing
happens concurrently with the next delivery?

Forgetting about the counters, the message ids that are logged at the
beginning with this line are still not fully ordered.
System.out.println("Consuming message " + message);

Therefore, we could process messages in the wrong order, which is a
situation we observed in an Apache Camel RabbitMQ consumer route (higher
level code). We noticed that after requeuing a message, the next message
consumed had a different id. It was actually switching between the first 2
messages, like there were two consumers.

If global prefetch has a different meaning, why isn't it equivalent to a
local prefetch in the situation of a single consumer? The doc says "shared
across all consumers on the channel".

Thank you.
Steven


Le dim. 21 juin 2020 à 19:28, Michael Klishin <notifications@github.com> a
écrit :

**Comment by michaelklishin** [comment]
For RabbitMQ to know that it can deliver another message with prefetch of 1, the `basic.{nack,reject}` frame has to reach the server. Once that happens, the following delivery can be concurrent because prefetch is a part of channel state and message index state is a part of the queue state. Channels and queues are separate stateful processes that communicate entirely asynchronously. A quick inspection of `rabbit_channel`'s `basic.reject` handler suggests that it notifies the queue asynchronously after updating its own state, so the queue can detect that the limit has been lifted before it finishes requeueing.

**Comment by michaelklishin** [comment]
It's a little bit more involved. Upon receiving a `basic.reject`, a channel would

 * Notify the queue about the operation
 * Notify the limiter (a stateful dependency that implements prefetch)
 * Update its own state

The limiter and queue processes do not coordinate but the queue performs the requeueing then "runs", that is, tries to deliver the next message at the head. I do not see how global prefetch can make any difference here. I also think all of this is a red herring because…

Because while your tests supposedly open a new connection per test, they *do not close it* which means you have two consumers on the shared queue by the time the second test runs. Injecting some sleeps and inspecting queue metrics (the number of consumers) will prove this hypothesis. How deliveries work with competing consumers is [explained in tutorial 2](https://www.rabbitmq.com/tutorials/tutorial-two-java.html). A traffic capture would demonstrate that the deliveries happen on different channels in the 2nd test.

**Comment by sdurrenmatt** [comment]
Thanks a lot for the details, it is pretty interesting to know how it
works! But if prefetch is part of the channel state as you said, would it
not seem consistent to observe some differences when it is applied directly
to the consumer? Maybe it is implemented differently?

I tried a lot of things (including AtomicInteger counters for the beauty of
it) and made sure to run my tests separately before... The queue is auto
delete but as you suggested I added the channel.close and connection.close
(quick look at the logs / user management interface confirms they are
closed after each test, and that the queue is deleted and recreated). I ran
the tests again and still got two different results.

with basicQos(1, false)
Consuming message 0
Consuming message 0
Consuming message 0
Consuming message 0
Consuming message 0
...

with basic.Qos(1, true)
Consuming message 0
Consuming message 1
Consuming message 0
Consuming message 0
Consuming message 0
...

Trying to requeue 10000 messages, the order is *never* broken with
basicQos(1, false), whereas it is (randomly at some times) with basicQos(1,
true).
Also in our real application we have two instances so we enabled SAC on the
queue to eliminate competing consumers and observed the same behavior.

I will try some Wireshark tomorrow (directly on our app) and hope to send
you some traffic capture.

Thank you.

Le dim. 21 juin 2020 à 22:54, Michael Klishin <notifications@github.com> a
écrit :

**Comment by michaelklishin** [comment]
@sdurrenmatt have you seen the part where I explained that your test has an unintended side effect of retaining consumers **on a shared queue** between tests? I'd focus on investigating that part first.

**Comment by kjnilsson** [comment]
Global QoS has an awkward implementation and is rarely used as it assumes you have multiple consumers in a single channel which isn't a very common pattern. We are considering/discussing deprecating this feature in the future. The new Quorum Queue queue type for example does _not_ support global QoS and it is likely future queue types will follow suite. based on this I would recommend you do not use or rely on global QoS even though at this point it isn't actually deprecated.

**Comment by sdurrenmatt** [comment]
Wireshark captures seem to confirm there is a difference of behavior (see #27 which should be the first redelivery of the first message)

**Basic.Qos Global: True**
```
1	0.000000	AMQP	Protocol-Header 0-9-1
2	0.001880	AMQP	Connection.Start 
3	0.038904	AMQP	Connection.Start-Ok 
4	0.039166	AMQP	Connection.Tune 
5	0.044859	AMQP	Connection.Tune-Ok 
6	0.045462	AMQP	Connection.Open vhost=/ 
7	0.045738	AMQP	Connection.Open-Ok 
8	0.053265	AMQP	Channel.Open 
9	0.053959	AMQP	Channel.Open-Ok 
10	0.056853	AMQP	Queue.Declare q=redelivery-order-with-qos-test 
11	0.062396	AMQP	Queue.Declare-Ok q=redelivery-order-with-qos-test 
12	0.064450	AMQP	Basic.Publish x= rk=redelivery-order-with-qos-test Content-Header Content-Body 
. . .
21	0.065071	AMQP	Basic.Publish x= rk=redelivery-order-with-qos-test Content-Header Content-Body 
22	0.065306	AMQP	Basic.Qos 
23	0.065776	AMQP	Basic.Qos-Ok 
24	0.068261	AMQP	Basic.Consume q=redelivery-order-with-qos-test 
25	0.068625	AMQP	Basic.Consume-Ok Basic.Deliver x= rk=redelivery-order-with-qos-test Content-Header Content-Body 
                                        Channel: 1
                                        Payload: 30
26	2.084068	AMQP	Basic.Reject 
27	2.084468	AMQP	Basic.Deliver x= rk=redelivery-order-with-qos-test Content-Header Content-Body 
                                        Channel: 1
                                        Payload: 31
28	4.085537	AMQP	Basic.Reject 
29	4.085916	AMQP	Basic.Deliver x= rk=redelivery-order-with-qos-test Content-Header Content-Body 
                                        Channel: 1
                                        Payload: 30
30	6.087179	AMQP	Basic.Reject 
31	6.087531	AMQP	Basic.Deliver x= rk=redelivery-order-with-qos-test Content-Header Content-Body 
                                        Channel: 1
                                        Payload: 30
32	8.088347	AMQP	Basic.Reject 
33	8.088763	AMQP	Basic.Deliver x= rk=redelivery-order-with-qos-test Content-Header Content-Body 
                                        Channel: 1
                                        Payload: 30
34	10.072485	AMQP	Channel.Close reply=OK 
35	10.078921	AMQP	Channel.Close-Ok 
36	10.081362	AMQP	Connection.Close reply=OK 
37	10.081663	AMQP	Connection.Close-Ok 
```

**Basic.Qos Global: False**
```
1	0.000000	AMQP	Protocol-Header 0-9-1
2	0.001733	AMQP	Connection.Start 
3	0.042334	AMQP	Connection.Start-Ok 
4	0.042789	AMQP	Connection.Tune 
5	0.049042	AMQP	Connection.Tune-Ok 
6	0.049791	AMQP	Connection.Open vhost=/ 
7	0.051093	AMQP	Connection.Open-Ok 
8	0.057360	AMQP	Channel.Open 
9	0.057986	AMQP	Channel.Open-Ok 
10	0.061247	AMQP	Queue.Declare q=redelivery-order-with-qos-test 
11	0.065446	AMQP	Queue.Declare-Ok q=redelivery-order-with-qos-test 
12	0.067657	AMQP	Basic.Publish x= rk=redelivery-order-with-qos-test Content-Header Content-Body 
. . .
21	0.068240	AMQP	Basic.Publish x= rk=redelivery-order-with-qos-test Content-Header Content-Body 
22	0.068514	AMQP	Basic.Qos 
23	0.069138	AMQP	Basic.Qos-Ok 
24	0.071791	AMQP	Basic.Consume q=redelivery-order-with-qos-test 
25	0.072206	AMQP	Basic.Consume-Ok Basic.Deliver x= rk=redelivery-order-with-qos-test Content-Header Content-Body 
                                        Channel: 1
                                        Payload: 30
26	2.088576	AMQP	Basic.Reject 
27	2.089043	AMQP	Basic.Deliver x= rk=redelivery-order-with-qos-test Content-Header Content-Body 
                                        Channel: 1
                                        Payload: 30
28	4.089158	AMQP	Basic.Reject 
29	4.089517	AMQP	Basic.Deliver x= rk=redelivery-order-with-qos-test Content-Header Content-Body
                                        Channel: 1
                                        Payload: 30
30	6.090511	AMQP	Basic.Reject 
31	6.090925	AMQP	Basic.Deliver x= rk=redelivery-order-with-qos-test Content-Header Content-Body
                                        Channel: 1
                                        Payload: 30
32	8.091925	AMQP	Basic.Reject 
33	8.092348	AMQP	Basic.Deliver x= rk=redelivery-order-with-qos-test Content-Header Content-Body 
                                        Channel: 1
                                        Payload: 30
34	10.074007	AMQP	Channel.Close reply=OK 
35	10.079726	AMQP	Channel.Close-Ok 
36	10.081993	AMQP	Connection.Close reply=OK 
37	10.082257	AMQP	Connection.Close-Ok 
```
[rabbitmq-qos-wireshark.zip](https://github.com/rabbitmq/discussions/files/4814938/rabbitmq-qos-wireshark.zip)

**Comment by sdurrenmatt** [comment]
@kjnilsson There is indeed no reason we should use global QoS in our Camel application, which creates as many channels as publishers/consumers. We also thought about using quorum queues for its redelivery limit feature, but they lack some other features we need.

Ended up using SAC queue with consumer QoS of 1, which does preserve message order in case of redelivery.

@michaelklishin Thank you again for the great support and enlightening information on how RabbitMQ works.

**Comment by michaelklishin** [comment]
@sdurrenmatt @Vanlightly managed to reproduce what you have seen. Our conclusion is that we will make it clear in the docs that we support ordering for non-redelivered messages but redelivered ones can be delivered out of order in some scenarios (in particular with prefetch > 1). This would be the case even if the asynchronous communication described above was made synchronous (doing so would have throughput and latency effects, of course).

Please take this into consideration when designing your system.
