### ISSUE TITLE
ObjectDisposedException channel.BasicAck version 3.8.5

### ISSUE THREAD

**Issue by LucaLodini** [rabbitmq/discussions#124]
HI using version 3.8.5 and Rabbit.Client 6.1 (net client) 
Following the tutorial Work Queues before updating to version 3.8.5, everything worked correctly, since yesterday, however, it signals the following exception ObjectDisposedException in the consumer to the following code  channel.BasicAck.

if I catch exception doing debugging channel presents ObjectDisposedException.

why?
Thanks

**Comment by michaelklishin** [comment]
One thing we can certainly say is that this is a client-side exception. Nothing has changed around consumer acknowledgements in years. You may be running into a [channel exception around acknowledgements](https://www.rabbitmq.com/confirms.html#consumer-acks-double-acking). They will be visible in [server logs](https://www.rabbitmq.com/logging.html).

Besides that my only guess is that your code has changed.

**Comment by LucaLodini** [comment]
Hi
The code running in localhost system w10 with version 3.8.3 with 3.8.5 ko

this is StackTrace:

Exception:    in RabbitMQ.Client.Impl.AutorecoveringModel.BasicAck(UInt64 deliveryTag, Boolean multiple) in /_/projects/RabbitMQ.Client/client/impl/AutorecoveringModel.cs:riga 748
   in ConsumerStandardService.ConsumerStandardService.<>c__DisplayClass8_1.<DoWork>b__0(Object model, BasicDeliverEventArgs ea) in ConsumerStandardService.cs:riga 84.

This is code :
var factory = new ConnectionFactory() { HostName = hostnameConf };
                    factory.AutomaticRecoveryEnabled = true;
                    factory.NetworkRecoveryInterval = TimeSpan.FromSeconds(10);
                    factory.TopologyRecoveryEnabled = true;

                    try
                    {
                        using (var connection = factory.CreateConnection())
                        using (var channel = connection.CreateModel())
                        {
                            channel.QueueDeclare(queue: "task_queue",
                                                durable: true,
                                                exclusive: false,
                                                autoDelete: false,
                                                arguments: null);

                            channel.BasicQos(prefetchSize: 0, prefetchCount: 1, global: false);

                            var consumer = new EventingBasicConsumer(channel);
                            consumer.Received += (model, ea) =>
                            {
                                var body = ea.Body;
                                var message = Encoding.UTF8.GetString(body.ToArray());
                                Thread.Sleep(10000);

                                channel.BasicAck(deliveryTag: ea.DeliveryTag, multiple: false); // ObjectDisposeException
                                //Save my Object
                            };

                            channel.BasicConsume(queue: "task_queue",
                                                 autoAck: false,
                                                 consumer: consumer);
                        }
                    }

thanks

Da: Michael Klishin<mailto:notifications@github.com>
Inviato: mercoledì 24 giugno 2020 16:13
A: rabbitmq/discussions<mailto:discussions@noreply.github.com>
Cc: Luca Lodini<mailto:luca.lodini@bitsrl.net>; Author<mailto:author@noreply.github.com>
Oggetto: Re: [rabbitmq/discussions] ObjectDisposedException thrown by channel.BasicAck with .NET client 6.1 (#124)


One thing we can certainly say is that this is a client-side exception. Nothing has changed around consumer acknowledgements in years. You may be running into a channel exception around acknowledgements<https://www.rabbitmq.com/confirms.html#consumer-acks-double-acking>. They will be visible in server logs<https://www.rabbitmq.com/logging.html>.

Besides that my only guess is that your code has changed.
