### ISSUE TITLE
Is it recommended to install VMware Tanzu RabbitMQ [VMs] v1.19 on AWS multiple AZs?

### ISSUE THREAD

**Issue by ichandan16** [rabbitmq/discussions#125]
Hi All, We are planning to install VMware Tanzu RabbitMQ [VMs] v1.19 on AWS multiple AZs. One of the [principles](https://docs.pivotal.io/rabbitmq-cf/1-19/ondemand.html#principles) suggests we should not install the RabbitMQ on multiple AZs to avoid latency. On the other hand we are unsure about how to provide the service in case of a single AWS AZ outage.

**Network Latency**

```

RabbitMQ clusters are only recommended for deployment in low latency networks, 
which normally means that it is not advisable to deploy these clusters across availability zones (AZs). 
The stability and performance of the RabbitMQ cluster is heavily influenced by the workload on the nodes, 
replication choices, and network latency.
 
For this reason, VMware recommends that you deploy RabbitMQ clusters into a single Ops Manager AZ.
However, where different AZs are in the same data center, with reliable low latency links, spanning AZs can be used.

```

Appreciate suggestions.

/r,
Chandan Patra

**Comment by michaelklishin** [comment]
You can find this discussed on the mailing list. Multiple AZ's within a region work quite well for most users as far as we can tell. A cluster must not span regions, however.

**Comment by michaelklishin** [comment]
Thank you for posting your question in this dedicated repo, by the way! 👍
