### ISSUE TITLE
Single-Active-Consumer recovery in HA scenario

### ISSUE THREAD

**Issue by Valinor** [rabbitmq/discussions#128]
Hi,
In HA scenario ( with 3 or more node ), I have a strange and problematic behavior with **single-active-consumer**.

**[ Tested on 3.8.3, 3.8.4 and 3.8.5 ]**
(if you have only one node, there is no problem, the recover work, but it's not really HA )

Classic Queue recover when node crash/restart/disconnect.
Classic Queue with Single-active-consumer don't recover when node crash/restart/disconnect.

When I have a consumer on the queue (example with master node for this queue is node1), and I restart the node, I have two different behavior:
- with classic queue : The consumer follow the new master node elected for this queue ( node 2, for example ), and we can see in management console that there is always a consumer on that queue.
- with single-active-consumer : The consumer never reconnect (to the new or the old node), and we can see in the management console that there is no consumer on that queue.

It is easy to reproduce, and to test.

In attachment, you can found : 
- A dockerfile with configuration to have a ha cluster.
- A script and a json definition to initialize queue and vHost on this cluster
- A very simple java consumer to launch two consumers, one on each queue (classic and with single active consumer).
- A readme to use it.

```

docker-compose up -d
./install.sh
cd rabbitSAC
mvn install
mvn exec:java -Dexec.mainClass="RabbitClientTest" -Dexec.classpathScope=runtime &
cd ..
```

Check in management console (localhost:15671) that each queue have a consumer.
To reproduce, find the node where the consumer are connected : 
- use the script ./test.sh before restarting and after and notice the problem

```
Test Rabbit >./test.sh
Management see connections on nodes :
rabbit@node3
rabbit@node2
Numbers on consumers on queue-nosac +1
Numbers on consumers on queue-sac +1
Test Rabbit >docker restart node3
node3
Test Rabbit >docker restart node2
node2
Test Rabbit >./test.sh
Management see connections on nodes :
rabbit@node3
rabbit@node1
Numbers on consumers on queue-nosac +1
Numbers on consumers on queue-sac +0
Test Rabbit >
```

You can notice, there is no more consumer on queue-sac, but the consumer is still present on node3

There is somes dependencies to test/for scripts ( docker, jq, curl, docker-compose )

**Update**
_Test with the python pika implementation_ because no recover in this implementation, so, try to recover manually

I have this time another funny behavior.

_To test, you should use a virtual env with pika, or install pika in your environment_

run :
```
./reveiver sac &
./reveiver nosac &

```
Now, run ./test.sh
```
./test.sh
"rabbit@node3 queue-sac"
"rabbit@node2 queue-nosac"
nosac consumer : 1
sac consumer : 1
```

Ok, now, kill the nosac node:
```
> docker restart node2
Connection closed. Recovering
> ./test.sh
"rabbit@node3 queue-sac"
"rabbit@node1 queue-nosac"
nosac consumer : 1
sac consumer : 1
> jobs
jobs
[1]+  Running                 python receiver.py nosac &
[2]+  Running                 python receiver.py sac &
>
```

Ok, now, kill the sac node:
```
> docker restart node3
Connection closed. Recovering
> ./test.sh
"rabbit@node1 queue-nosac"
nosac consumer : 1
sac consumer : 0
> jobs
jobs
[1]+  Running                 python receiver.py nosac &
>
```
The process disappear, quit a infinite loop without any exception or trace.

I attached a new and more complete testbed to the issue to reproduce the behavior (the python receiver, and a update ./test.sh)

[sac-test.tar.gz](https://github.com/rabbitmq/discussions/files/4862973/sac-test.tar.gz)
[sac-test-v2.zip](https://github.com/rabbitmq/discussions/files/4864123/sac-test-v2.zip)

**Comment by michaelklishin** [comment]
Thanks for providing some details on your test. Without spending some time to run it and any logs, there are things that stand out from a quick inspection of your test.

Your steps include a restart for a node that the consumer is connected to but at least your Java example does not [recover from connection failures](https://www.rabbitmq.com/api-guide.html#recovery) in any way. You should be able to [see connection events](https://www.rabbitmq.com/logging.html#connection-lifecycle-events) in node logs if it did.

With a regular consumer, when queue master replica migrates, RabbitMQ will re-register consumers connected to other nodes after a promotion event. IIRC this was introduced in 3.4.0. It assumes that channels on other nodes with connected consumers on them can observe a leadership transfer. I don't see any [SAC special casing](https://github.com/rabbitmq/rabbitmq-server/blob/master/src/rabbit_channel.erl#L1884) in that scenario.

Given SAC the assumption is that you already have multiple competing consumers on a queue at all times, so the same kind of "re-registration" may or may not be a sensible thing to do.

@acogoluegnes @Vanlightly does this sound like a scenario we have tested or "special-cased" SACs for?

[SAC test suite](https://github.com/rabbitmq/rabbitmq-server/blob/master/test/single_active_consumer_SUITE.erl) does not include a scenario described here (where classic mirrored queue primary moves during the test).

**Comment by michaelklishin** [comment]
(we close all issues that are discussions, new specific ones will be filed if/when we have evidence of something that our team believes should be addressed in RabbitMQ, docs or one of the clients)

**Comment by acogoluegnes** [comment]
> @acogoluegnes @Vanlightly does this sound like a scenario we have tested or "special-cased" SACs for?

No, it does not, as far as I remember.

**Comment by Valinor** [comment]
> to but at least your Java example does not recover from connection failures in any way. You should be able to see connection events in node logs if it did.

**setAutomaticRecoveryEnabled** is, by default, set to true in java client : see
[(https://github.com/rabbitmq/rabbitmq-java-client/blob/ef5142e8a0ec89e0e9d137cd1cdff0276f3ba76c/src/main/java/com/rabbitmq/client/ConnectionFactory.java#L805)] 
and
[(https://github.com/rabbitmq/rabbitmq-java-client/blob/ef5142e8a0ec89e0e9d137cd1cdff0276f3ba76c/src/main/java/com/rabbitmq/client/ConnectionFactory.java#L124)]

I also make a manual reconnection in python to show my point, and compare with classic client behavior.

**About log**
on new master node : 
```2020-07-03 09:12:56.217 [error] <0.1174.0> ** Generic server <0.1174.0> terminating
** Last message in was {'$gen_cast',{force_event_refresh,#Ref<17321.3056101955.2660499457.69706>}}
** When Server state == {q,{amqqueue,{resource,<<"myVhost">>,queue,<<"queue-sac">>},true,false,none,[{<<"x-dead-letter-exchange">>,longstr,<<>>},{<<"x-dead-letter-routing-key">>,longstr,<<"queue-sac-dlq">>},{<<"x-max-priority">>,long,10},{<<"x-single-active-consumer">>,bool,true}],<0.1174.0>,[<17320.1063.0>,<17321.613.0>],[<17321.613.0>,<17320.1063.0>],[rabbit@node1,rabbit@node2],[{vhost,<<"myVhost">>},{name,<<"HA">>},{pattern,<<".*">>},{'apply-to',<<"all">>},{definition,[{<<"ha-mode">>,<<"all">>},{<<"ha-sync-mode">>,<<"automatic">>}]},{priority,5}],undefined,[{<17321.614.0>,<17321.613.0>},{<17320.1064.0>,<17320.1063.0>},{<0.1194.0>,<0.1174.0>}],[],live,0,[],<<"myVhost">>,#{user => <<"admin">>},rabbit_classic_queue,#{}},{<0.1732.0>,{consumer,<<"ctag1.1dd33310f288425eaf6755dfd39c548d">>,false,0,[],<<"admin">>}},true,rabbit_mirror_queue_master,{state,{resource,<<"myVhost">>,queue,<<"queue-sac">>},<0.1194.0>,<0.1193.0>,rabbit_priority_queue,{state,rabbit_variable_queue,[{10,{vqstate,{0,{[],[]}},{0,{[],[]}},{delta,undefined,0,0,undefined},{0,{[],[]}},{0,{[],[]}},0,{0,nil},{0,nil},{0,nil},{qistate,"/var/lib/rabbitmq/mnesia/rabbit@node3/msg_stores/vhosts/9WONPZ5BCPG71PT9D0E3GNUD6/queues/9IEZAG55WKOUS4DL6QUFU25KF",{#{},[]},undefined,0,32768,#Fun<rabbit_variable_queue.2.43870038>,#Fun<rabbit_variable_queue.3.43870038>,{0,nil},{0,nil},[],[],{resource,<<"myVhost">>,queue,<<113,117,101,117,101,45,115,97,99,0,10>>}},{{client_msstate,<0.1137.0>,<<3,113,235,143,172,166,232,149,229,74,8,187,38,97,143,187>>,#{},{state,#Ref<0.2701879643.4001759233.6680>,"/var/lib/rabbitmq/mnesia/rabbit@node3/msg_stores/vhosts/9WONPZ5BCPG71PT9D0E3GNUD6/msg_store_persistent"},rabbit_msg_store_ets_index,"/var/lib/rabbitmq/mnesia/rabbit@node3/msg_stores/vhosts/9WONPZ5BCPG71PT9D0E3GNUD6/msg_store_persistent",<0.1140.0>,#Ref<0.2701879643.4001759233.6681>,#Ref<0.2701879643.4001759233.6676>,#Ref<0.2701879643.4001759233.6682>,...},...},...}},...],...},...},...}
** Reason for termination == 
** {{badmatch,[{<0.1732.0>,<<"ctag1.1dd33310f288425eaf6755dfd39c548d">>,false,0,true,up,[],<<"admin">>}]},[{rabbit_amqqueue_process,handle_cast,2,[{file,"src/rabbit_amqqueue_process.erl"},{line,1646}]},{gen_server2,handle_msg,2,[{file,"src/gen_server2.erl"},{line,1067}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,236}]}]}
2020-07-03 09:12:56.218 [error] <0.1174.0> CRASH REPORT Process <0.1174.0> with 2 neighbours exited with reason: no match of right hand value [{<0.1732.0>,<<"ctag1.1dd33310f288425eaf6755dfd39c548d">>,false,0,true,up,[],<<"admin">>}] in rabbit_amqqueue_process:handle_cast/2 line 1646 in gen_server2:terminate/3 line 1183
2020-07-03 09:12:56.218 [error] <0.1173.0> Supervisor {<0.1173.0>,rabbit_amqqueue_sup} had child rabbit_amqqueue started with rabbit_prequeue:start_link({amqqueue,{resource,<<"myVhost">>,queue,<<"queue-sac">>},true,false,none,[{<<"x-dead-letter-exch...">>,...},...],...}, declare, <0.1172.0>) at <0.1174.0> exit with reason no match of right hand value [{<0.1732.0>,<<"ctag1.1dd33310f288425eaf6755dfd39c548d">>,false,0,true,up,[],<<"admin">>}] in rabbit_amqqueue_process:handle_cast/2 line 1646 in context child_terminated
2020-07-03 09:12:56.239 [info] <0.1724.0> closing AMQP connection <0.1724.0> (172.18.0.4:37502 -> 172.18.0.5:5672, vhost: 'myVhost', user: 'admin')
```

From pika, if I really want to force reconnection, I have : 
```
pika.exceptions.ChannelClosedByBroker: (404, "NOT_FOUND - queue 'queue-sac' in vhost 'myVhost' has crashed and failed to restart")
```

and on the node : 
```
2020-07-03 09:26:00.119 [info] <0.3402.0> Mirrored queue 'queue-sac-dlq' in vhost 'myVhost': Synchronising: all slaves already synced

2020-07-03 09:26:00.672 [info] <0.3417.0> accepting AMQP connection <0.3417.0> (172.18.0.4:39540 -> 172.18.0.5:5672)
2020-07-03 09:26:00.675 [info] <0.3417.0> connection <0.3417.0> (172.18.0.4:39540 -> 172.18.0.5:5672): user 'admin' authenticated and granted access to vhost 'myVhost'
2020-07-03 09:26:00.679 [error] <0.3425.0> Channel error on connection <0.3417.0> (172.18.0.4:39540 -> 172.18.0.5:5672, vhost: 'myVhost', user: 'admin'), channel 1:
operation basic.consume caused a channel exception not_found: queue 'queue-sac' in vhost 'myVhost' has crashed and failed to restart
2020-07-03 09:26:00.689 [warning] <0.3417.0> closing AMQP connection <0.3417.0> (172.18.0.4:39540 -> 172.18.0.5:5672, vhost: 'myVhost', user: 'admin'):
client unexpectedly closed TCP connection
2020-07-03 09:26:00.781 [info] <0.1818.0> Mirrored queue 'queue-sac' in vhost 'myVhost': Promoting slave <rabbit@node3.1593767195.1818.0> to master
```

Seem to me that the node accept the connection too early or something like that.

How can I help you more ?

**Comment by acogoluegnes** [comment]
Thanks for the information you provided, we'll try to reproduce and investigate as soon as time allows. You can also experiment the behavior of SAC with [quorum queues](https://www.rabbitmq.com/quorum-queues.html), they're the next generation of mirrored queues and their SAC implementation may have been more tested that the one of classic queues.

**Comment by michaelklishin** [comment]
So there is a queue process exception, we will try to reproduce. Please use quorum queues for now and in general, if you can.

**Comment by Vanlightly** [comment]
I tested this scenario heavily during the SAC beta phase and up to 3.8.0 release but I haven't tested these versions. I will run my chaos tester with this scenario and see if I can reproduce.

**Comment by Valinor** [comment]
> Please use quorum queues for now and in general, if you can.

I tested quorum queue, and it's work like a charm. Thanks for the tips.

Currently quorum still lack some functionalities that i need (TTL and priority), but indeed, it's works.

**Comment by Vanlightly** [comment]
All my test of SAC use manual reconnection with Pika so did not pick up on this. 

However, I ran the test with the .NET client as I have env set up with it already. I do not ever see the queue not found error, but I do get the situation where reconnection fails to happen. The connection and channel remain active but the consumer is gone.

This coincides with killing a broker and this error happening in the logs.

`2020-07-07 12:40:27.855 [error] <0.573.0> ** Generic server <0.573.0> terminating
** Last message in was {'$gen_cast',{force_event_refresh,#Ref<18289.2187371737.95682562.41349>}}
** When Server state == {q,{amqqueue,{resource,<<"/">>,queue,<<"test1">>},true,false,none,[{<<"x-queue-type">>,longstr,<<"classic">>},{<<"x-single-active-consumer">>,bool,true}],<0.573.0>,[<18288.10565.0>,<18289.572.0>],[<18289.572.0>,<18288.10565.0>],[rabbit@rabbitmq3,rabbit@rabbitmq1],[{vhost,<<"/">>},{name,<<"ha">>},{pattern,<<>>},{'apply-to',<<"queues">>},{definition,[{<<"ha-mode">>,<<"all">>},{<<"ha-sync-mode">>,<<"automatic">>}]},{priority,0}],undefined,[{<18289.573.0>,<18289.572.0>},{<18288.10567.0>,<18288.10565.0>},{<0.574.0>,<0.573.0>}],[],live,1,[],<<"/">>,#{user => <<"guest">>},rabbit_classic_queue,#{}},{<0.1086.0>,{consumer,<<"amq.ctag-Tnh8_KyqFAn5ISNpDfoFHw">>,true,10,[],<<"guest">>}},true,rabbit_mirror_queue_master,{state,{resource,<<"/">>,queue,<<"test1">>},<0.574.0>,<0.1035.0>,rabbit_priority_queue,{passthrough,rabbit_variable_queue,{vqstate,{0,{[],[]}},{0,{[],[]}},{delta,undefined,0,0,undefined},{0,{[],[]}},{0,{[],[]}},122,{0,nil},{0,nil},{0,nil},{qistate,"/var/lib/rabbitmq/mnesia/rabbit@rabbitmq2/msg_stores/vhosts/628WB79CIFDYO9LJI6DKMI09L/queues/8S89WE1HG3OO8W4GVEKO1IIO5",{#{},[{segment,0,"/var/lib/rabbitmq/mnesia/rabbit@rabbitmq2/msg_stores/vhosts/628WB79CIFDYO9LJI6DKMI09L/queues/8S89WE1HG3OO8W4GVEKO1IIO5/0.idx",{array,16384,0,undefined,{{{{{undefined,{no_pub,no_del,ack},{no_pub,no_del,ack},{no_pub,no_del,ack},{no_pub,no_del,ack},{no_pub,no_del,ack},{no_pub,no_del,ack},{no_pub,no_del,ack},{no_pub,no_del,ack},{no_pub,no_del,ack}},{{no_pub,no_del,ack},{no_pub,no_del,ack},{no_pub,no_del,ack},{no_pub,no_del,ack},{no_pub,no_del,ack},{no_pub,no_del,ack},{no_pub,no_del,ack},{no_pub,no_del,ack},{no_pub,no_del,ack},{no_pub,no_del,ack}},{{no_pub,no_del,ack},{no_pub,no_del,ack},{no_pub,no_del,ack},{no_pub,no_del,ack},{no_pub,no_del,ack},{no_pub,no_del,ack},{no_pub,no_del,ack},{no_pub,no_del,ack},{no_pub,no_del,ack},{no_pub,no_del,ack}},{{no_pub,no_del,ack},{no_pub,no_del,...},...},...},...},...},...}},...}]},...},...}},...},...}
** Reason for termination == 
** {{badmatch,[{<0.1086.0>,<<"amq.ctag-Tnh8_KyqFAn5ISNpDfoFHw">>,true,10,true,up,[],<<"guest">>}]},[{rabbit_amqqueue_process,handle_cast,2,[{file,"src/rabbit_amqqueue_process.erl"},{line,1646}]},{gen_server2,handle_msg,2,[{file,"src/gen_server2.erl"},{line,1067}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,236}]}]}
2020-07-07 12:40:27.856 [error] <0.573.0> CRASH REPORT Process <0.573.0> with 2 neighbours exited with reason: no match of right hand value [{<0.1086.0>,<<"amq.ctag-Tnh8_KyqFAn5ISNpDfoFHw">>,true,10,true,up,[],<<"guest">>}] in rabbit_amqqueue_process:handle_cast/2 line 1646 in gen_server2:terminate/3 line 1183
2020-07-07 12:40:27.856 [error] <0.572.0> Supervisor {<0.572.0>,rabbit_amqqueue_sup} had child rabbit_amqqueue started with rabbit_prequeue:start_link({amqqueue,{resource,<<"/">>,queue,<<"test1">>},true,false,none,[{<<"x-queue-type">>,longstr,<<"cl...">>},...],...}, slave, <0.571.0>) at <0.573.0> exit with reason no match of right hand value [{<0.1086.0>,<<"amq.ctag-Tnh8_KyqFAn5ISNpDfoFHw">>,true,10,true,up,[],<<"guest">>}] in rabbit_amqqueue_process:handle_cast/2 line 1646 in context child_terminated`

**Comment by Vanlightly** [comment]
Also, it should be noted that the amqp consumers crash when the node that was killed is restarted, and syncing is complete. If I kill a node and a fail-over occurs, then reconnection works fine. I leave it a few minutes, consumption continues fine. Then I bring back the dead node, syncing completes and then the consumers crash, leaving the channel intact.

I reviewed the logs from running my Pika based manual reconnection tests and I see the same broker errors but also the queue crashed error. This error repeats for a while as the manual reconnects occur until the queue recovers.
