### ISSUE TITLE
When the machine goes down, the binding for the delayed switch cannot be routed

### ISSUE THREAD

**Issue by dong9205** [rabbitmq/discussions#139]
HI, When all of my nodes went down, I found that the binding of the delayed switch had to be re-bound, and the routing could not be done without re-binding.

**Comment by dong9205** [comment]
I can guarantee that it is persistent, and when I restart, I can see the binding content and unconsumed information, but when I send the information to the switch again, I will be prompted that I cannot find the route.The version of RabbitMQ-Server used is 3.8.4.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rabbitmq/discussions"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月3日(星期四) 上午10:43
收件人:&nbsp;"rabbitmq/discussions"<discussions@noreply.github.com&gt;;
抄送:&nbsp;"董大轩"<920506213@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [rabbitmq/discussions] When the machine goes down, the binding for the delayed switch cannot be routed (#139)





 
Another important factor is whether the queues bound to this exchange are durable. If they are not, then their bindings cannot be durable either.

**Comment by michaelklishin** [comment]
@dong9205 another reason can be publishing with the immediate flag which is not supported by this exchange (also covered in the README). Specifically with `3.8.4`, https://github.com/rabbitmq/rabbitmq-server/issues/2177 could be relevant.

Without steps to reproduce, server logs or binding listing there is nothing that can be suggested. We do not guess in this community, it is too time consuming for everyone involved.

**Comment by dong9205** [comment]
I tried version 3.8.6 of single node and still found the problem. My detailed steps are as follows
1. Create delay switch, bind topCI queue, send TTL 10s message, I can see the message arrives in the queue normally.
2. Send another message with the 10-second TTL. When it does not reach the queue, I perform RabbitMQCTL shutdown. Then, after 10 seconds, I perform the RabbitMQ-server rotarystartup and discover that the message cannot reach the queue.
3. Send a Message to the switch again, found that the news will never reach the queue. I try to use rabbitmq_management console to send, you will be prompted me "Message published, but not routed".
![image](https://user-images.githubusercontent.com/40266166/92195096-c1aff880-ee9e-11ea-8e9c-6f1d2d41595b.png)

**Comment by michaelklishin** [comment]
When publishing [without publisher confirms](https://www.rabbitmq.com/confirms.html), there *aren't any [publisher-side data safety](https://www.rabbitmq.com/publishers.html#data-safety) guarantees*, with this plugin or in general.

I assume by "TTL" you mean "publishing delay". Actual message TTL will make sure that the message is effectively deleted after that period of time. This plugin [operates](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/blob/master/src/rabbit_delayed_message.erl#L169) by using final publishing timestamps computed as Current Time + Delay and setting up a timer for the shortest pending delay known. A node restart will preserve the rows and keys but will mess up the timers. So this plugin offers limited publisher-side data safety even regardless of the use of publisher confirms.

HTTP API publishing endpoint [sets the `mandatory` flag to `true`](https://github.com/rabbitmq/rabbitmq-management/blob/master/src/rabbit_mgmt_wm_exchange_publish.erl#L59) which this plugin **explicitly does not and cannot support**.
