### ISSUE TITLE
Client isn't being notified in case of unroutable publishes

### ISSUE THREAD

**Issue by EdwardSkrobala** [rabbitmq/discussions#14]
## Summary

Our team faced up with issue on our production environment - after RabbitMQ maintance all queues were deleted and our client is still publishing messages without any error. 
We've prepared a short Pub/Sub demo reproducing it (https://github.com/EdwardSkrobala/MqttIssue).

Publisher & Subscriber connect to broker via websockets, publisher sends message every 5 sec with Qos-1 level set.
We need publisher to be acknowledged if it publishes message that is not delivered to subscriber.

## Environment:
* .NET Core 3.0
* RabbitMQ 3.7
* Plugin: Mqtt
* Client Lib: MQTTnet (https://github.com/chkr1011/MQTTnet)

## Steps to reproduce:
* Run `docker-compose -f docker-compose-brokers.yml up` from root folder
* Run `dotnet run` from project folder (src/Test/)
* Trigger management UI - http://localhost:15672/#/queues (username="test", pass="test")
* Delete Queue `mqtt-subscription-subscriberqos1` to simulate maintance on server.

## Code lines showing issue
Message configuration
`var message = new MqttApplicationMessageBuilder()
                .WithTopic("MyTopic")
                .WithPayload($"Hello World [{DateTime.Now.ToLongTimeString()}]")
                .WithQualityOfServiceLevel(MQTTnet.Protocol.MqttQualityOfServiceLevel.AtLeastOnce)
                .WithRetainFlag(false)
                .Build()`
PublishAsync returns MqttClientPublishResult  containing MqttClientPublishReasonCode (https://github.com/chkr1011/MQTTnet/blob/master/Source/MQTTnet/Client/Publishing/MqttClientPublishResult.cs)
`var publishResult = await publisherClient.PublishAsync(message)`

**Expected result:**
Exception or MqttClientPublishResult.ReasonCode = MqttClientPublishReasonCode.NoMatchingSubscribers

**Actual result:**
MqttClientPublishResult.ReasonCode = Success

Thanks in advance for the assistance

**Comment by michaelklishin** [comment]
It's also worth mentioning that with QoS 1, clients are [expected to treat publishes that haven't received a `PUBACK` frame as unacknowledged](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/csprd02/mqtt-v3.1.1-csprd02.html#_Toc385349835). In other words, the protocol only has positive acknowledgment frames but not negative ones. This is unfortunate because in some cases RabbitMQ would be able to send a specific enough negative acknowledgment and it does for the protocols that have such a feature.

Such publishers are also expected to [retry sending unacknowledged publishes](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/csprd02/mqtt-v3.1.1-csprd02.html#_Toc385349839), which sometimes makes sense and is safe but sometimes is not.

**Comment by michaelklishin** [comment]
The above sections make me wonder what could RabbitMQ do for such cases with QoS 1. We can (asynchronously) detect a condition where there is nowhere for a message to be routed to (no queues) but there is no protocol frame that would tell the client about it. The proposed course of action is to… do nothing and not send a `PUBACK`, which we already effectively do. Clients would have to have an acknowledgment timeout of some kind.

Let me know if you have ideas as to what we could do given that MQTT is not an extensible protocol. Maybe things are different in MQTT 5, which we plan to support in a future release.

RabbitMQ 3.8 has a new metric for unroutable messages exposed via our [Grafana dashboards](https://www.rabbitmq.com/prometheus.html) and management UI/HTTP API. I see no reason why in the described scenario such messages would not register there. So perhaps with the current state of MQTT protocol's approach to error reporting to clients, it can only be treated as a metric/observability problem.

**Comment by EdwardSkrobala** [comment]
@michaelklishin Thanks a lot for your help. For now we could see bigger picture and will try to investigate ways of workaround.
