### ISSUE TITLE
consumer no support for multi ip instance 

### ISSUE THREAD

**Issue by albertcoolsea** [rabbitmq/discussions#140]
Hello professors，
Consumer service deployed 2 JVM instance  on 2 
physical machines（A:192.xx.xx.a、B:192.xx.xx.b) ，concurrency = 10 ，the 2 JVM A starting firstly，so the 10 consumers’ ip is 192.xx.xx.a, 
192.xx.xx.b registered none consumer to the broker. in the condition, i have 2question，
1. how to confim consumer HA( A breakdown，B can be used?）
2. when jvm starting, how to make A 、B  both register consumers to broker?
    look forward to yours answer,thanks!

**Comment by acogoluegnes** [comment]
> 1. how to confim consumer HA( A breakdown，B can be used?）

The broker nodes need to be [clustered](https://www.rabbitmq.com/clustering.html) and the queues need to be [mirrored](https://www.rabbitmq.com/ha.html) or be [quorum queues](https://www.rabbitmq.com/quorum-queues.html) (preferred). 

The consumer HA is more of a client application concern than the broker's. If B is considered a passive node, it should detect A is down and start consuming. Nevertheless RabbitMQ 3.8 introduced [single active consumer](https://www.rabbitmq.com/consumers.html#single-active-consumer) that should help you to implement so passive/active consumer feature. You are encouraged to use single active consumer with [quorum queues](https://www.rabbitmq.com/quorum-queues.html).

> 2. when jvm starting, how to make A 、B  both register consumers to broker?

With single active consumer, A and B can register consumers on the same queue at the same time, only one will be enabled (understand "messages will be delivered to it").

**Comment by michaelklishin** [comment]
Also highly relevant here: [connection recovery support in the Java client](https://www.rabbitmq.com/api-guide.html#recovery).

**Comment by albertcoolsea** [comment]
> Also highly relevant here: [connection recovery support in the Java client](https://www.rabbitmq.com/api-guide.html#recovery).

could u give me some explain? please

**Comment by albertcoolsea** [comment]
> > 1. how to confim consumer HA( A breakdown，B can be used?）
> 
> The consumer HA is more of a client application concern than the broker's. If B is considered a passive node, it should detect A is down and start consuming. Nevertheless RabbitMQ 3.8 introduced [single active consumer](https://www.rabbitmq.com/consumers.html#single-active-consumer) that should help you to implement so passive/active consumer feature. You are encouraged to use single active consumer with [quorum queues](https://www.rabbitmq.com/quorum-queues.html).
> 
> > 1. when jvm starting, how to make A 、B  both register consumers to broker?
> 
> With single active consumer, A and B can register consumers on the same queue at the same time, only one will be enabled (understand "messages will be delivered to it").

thanks,
![image](https://user-images.githubusercontent.com/39090441/92364743-187b3380-f126-11ea-8620-ae3e75b4d15c.png)

 prd with apollo config center,after i restarting  rabbitMq cluster,   A,B IP both register to broker cluster ,just like this picture show that .
before restaring rabbitMq cluster , A or B just one can register to rabiitMq, this question i will keep looking.

"spring.rabbitmq.listener.simple.concurrency=10" ,
isn`t  it meaning  10 consumers can concurrency take message from the queue ignoring 10 consumers belong to A or B? 
![image](https://user-images.githubusercontent.com/39090441/92366437-bae7e680-f127-11ea-9b8e-2d2e2066e6b9.png)
so the words underline red line may are problems in expression,is it right?

**Comment by michaelklishin** [comment]
Spring AMQP listeners ultimately control how many threads a consumer registered in your apps will process consumer deliveries. It is entirely unaware of the Single Active Consumer mode that may be applicable.

I'm afraid I do not understand what you mean by "A, B IP both register". With Single Active Consumer, there will be multiple consumers registered but only one of them will get actual deliveries. Nonetheless other consumers will be known to RabbitMQ and "reigstered" in every other sense.
