### ISSUE TITLE
POST on user doesn't pass username and password

### ISSUE THREAD

**Issue by gbaranski** [rabbitmq/discussions#143]
Hello, as in title, POST doesn't pass username and password, but GET does.

**Comment by michaelklishin** [comment]
It's not obvious what your expectations are. Please clarify them.

`POST` requests issued by the plugin [will not have a query](https://github.com/rabbitmq/rabbitmq-auth-backend-http/blob/master/src/rabbit_auth_backend_http.erl#L133) but they should [contain a request body (as form parameters)](https://github.com/rabbitmq/rabbitmq-auth-backend-http#what-must-my-web-server-do).

[Enabling debug logging](https://www.rabbitmq.com/logging.html#debug-logging) will log a fair amount of details about the issued requests. A traffic capture on the target RabbitMQ node (or the service one) will tell everything there is.
