### ISSUE TITLE
Vhost Description and Tags are not available in RabbitMQ Cluster

### ISSUE THREAD

**Issue by argonius2412** [rabbitmq/discussions#145]
We are running RabbitMQ Cluster (3.8.8) with Erlang (23.0.4)

We have noticed, that descriptions and tags of vhosts are not available in the cluster.

### To reproduce in an existing cluster:
**Create /test3**
curl -i -XPUT -H "content-type:application/json" -u 'guest:guest'  -d '{"description":"test3 description", "tags":"test3-tag"}'  http://localhost:15672/api/vhosts/%2ftest3 
**Fetch information about vhost**
curl -i -u 'guest:guest'  http://localhost:15672/api/vhosts/%2ftest3 

### Expected:
An error that it is not possible to store description and tag in cluster or the output of the set description and tag

### Output:
Vhost defintion without the fields description and tag

**Comment by michaelklishin** [comment]
I cannot reproduce:

```
 curl -i -XPUT -H "content-type:application/json" -u 'guest:guest' -d '{"description":"test3 description", "tags":"test3-tag"}' http://localhost:15672/api/vhosts/%2ftest3
HTTP/1.1 201 Created
content-length: 0
content-security-policy: script-src 'self' 'unsafe-eval' 'unsafe-inline'; object-src 'self'
date: Wed, 23 Sep 2020 10:14:00 GMT
server: Cowboy
vary: accept, accept-encoding, origin
```

```
curl -i -u 'guest:guest' http://localhost:15672/api/vhosts/%2ftest3
HTTP/1.1 200 OK
cache-control: no-cache
content-length: 200
content-security-policy: script-src 'self' 'unsafe-eval' 'unsafe-inline'; object-src 'self'
content-type: application/json
date: Wed, 23 Sep 2020 10:14:07 GMT
server: Cowboy
vary: accept, accept-encoding, origin

{"name":"/test3","description":"test3 description","tags":["test3-tag"],"metadata":{"description":"test3 description","tags":["test3-tag"]},"tracing":false,"cluster_state":{"rabbit@warp10":"running"}}
```

**Comment by michaelklishin** [comment]
Virtual host description and tags are enabled by a [feature flag](https://www.rabbitmq.com/feature-flags.html) named `virtual_host_metadata`. it must be enabled or those fields won't exist in the virtual hosts table. See

```
rabbitmqctl help list_feature_flags
rabbitmqctl help enable_feature_flag
```

Depending on the history of your deployment and action taken during upgrades, it may or may not be enabled.

**Comment by argonius2412** [comment]
Thanks, the plugin was not enabled. Did it via webinterface (click on 'enable'). Now it works

**Comment by michaelklishin** [comment]
The feature flag. There are no plugins involved.

Every node logs its known set of feature flags and their state on boot, something similar to

```
2020-09-23 09:25:34.182 [debug] <0.1146.0> Feature flags: (re)initialize registry (<0.1146.0>)
2020-09-23 09:25:34.182 [info] <0.1146.0> Feature flags: list of feature flags found:
2020-09-23 09:25:34.182 [info] <0.1146.0> Feature flags:   [ ] implicit_default_bindings
2020-09-23 09:25:34.182 [info] <0.1146.0> Feature flags:   [~] maintenance_mode_status
2020-09-23 09:25:34.182 [info] <0.1146.0> Feature flags:   [ ] quorum_queue
2020-09-23 09:25:34.183 [info] <0.1146.0> Feature flags:   [ ] user_limits
2020-09-23 09:25:34.183 [info] <0.1146.0> Feature flags:   [ ] virtual_host_metadata
```

**Comment by argonius2412** [comment]
Sure, feature flag. I used the wrong term  ;)
Is there a way to add description + tags to existing vhosts? Or should we create a feature request for that?

**Comment by michaelklishin** [comment]
Both virtual host description and tags are immutable and meant to be set at creation time.
