### ISSUE TITLE
work queue - create 200 channels on one connection to create 200 consumers to consume one queue

### ISSUE THREAD

**Issue by turnhead** [rabbitmq/discussions#148]
RabbitMQ version & Erlang version:
RabbitMQ 3.3.3, Erlang 17 
amqp-client: 4.0.0

I want to create 200 consumer threads to consume one queue with round-robin dispatching to improve throughput, as the code following:
`
          while (count.get() < 200) {
                
                Channel channelx = connection.createChannel();
                
                channelx.queueDeclare("work_queue_hello", false, false, false, null);
                
                int index = count.get();
                
                Consumer consumerx = new DefaultConsumer(channel){
                    @Override
                    public void handleDelivery(String consumerTag, Envelope envelope, AMQP.BasicProperties properties, byte[] body) throws IOException {
                        
                        logger.info("start run limit consumer-{}....", index);
                        
                        
                        try {
                            Thread.sleep(10*1000);
                        } catch (InterruptedException e) {
                            // TODO Auto-generated catch block
                           
                        }

                    }
                };
                
                channelx.basicConsume("work_queue_hello",autoAck,consumerx);
                count.incrementAndGet();
            }
`

I think 200 threads are running simultaneously when hundreds of messages are incoming, but I find that only eight consumer threads not 200 threads are running at the same time, please tell me why , thank you!

**Comment by michaelklishin** [comment]
All deliveries are [dispatched to a thread pool with a per-channel ordering guarantee](https://www.rabbitmq.com/api-guide.html#concurrency), so for 200 threads to be active concurrently, the [thread pool used](https://www.rabbitmq.com/api-guide.html#consumer-thread-pool) must have enough threads (or be able to dynamically grow up to 200 threads).

On top of that, up to 200 (or more) outstanding unacknowledged deliveries must be [allowed on the channel](https://www.rabbitmq.com/confirms.html#channel-qos-prefetch) used to consume (or all channels used to consume in total).

RabbitMQ 3.3 has reached its end of life [in March 2015](https://www.rabbitmq.com/versions.html). The most recent version of RabbitMQ Java client is [5.9.0](https://www.rabbitmq.com/api-guide.html), which will be able to connect to RabbitMQ 3.3 but not features will be available. Channel prefetch will be, however, these versions are badly overdue for upgrading. The client library can be upgraded first.
