### ISSUE TITLE
Unable to consume from sharded "pseudo" queue

### ISSUE THREAD

**Issue by julienbonastre** [rabbitmq/discussions#149]
I am unsure as to why this occurs but I receive a 404 NOT_FOUND Fault trying to connect a consumer to this queue (via Python Pika 1.1.0 package)

Is this an issue related to pika specifically or the way in which RMQ shard plugin is not handling the amqp consumer "basic consume" request?
![image](https://user-images.githubusercontent.com/71309253/94778481-b4881a00-0408-11eb-97cc-805c3695619e.png)

![image](https://user-images.githubusercontent.com/71309253/94778416-8e627a00-0408-11eb-916d-f93b7352a51c.png)

**Comment by michaelklishin** [comment]
Reasons for [channel exceptions](https://www.rabbitmq.com/channels.html#error-handling) in this case may vary from connecting to an incorrect virtual host to mismatching declaration arguments. Server logs will contain details.

I will try to reproduce but there is no special support that Pika or any other client has to implement.

**Comment by julienbonastre** [comment]
Firstly, thank you @michaelklishin  for your super prompt response, this is my first Github issue post ever so thank you for being considerate and gentle on me 🤗 

So, I have confirmed the vhost being connected to is the correct one, and there is definitely no explicit declaration, binding or otherwise being requested in attempts I am making to use these pseudo-queues from the pika 1.1.0 amqp client - however unsure by your statement if I am _supposed_ to be utilising some particular declaration of the queue or otherwise.

I have followed the steps within https://github.com/rabbitmq/rabbitmq-sharding to the letter (even though the examples change the name of the exchange from shard.images to images in different sections - however this is just semantics)

So my rabbitmqctl status is at: https://slack-files.com/T307L90UD-F01CG3Q4AU8-51c6971b17
extract of key info:
`OS: Linux
Uptime (seconds): 36049
RabbitMQ version: 3.8.3
Node name: rabbit@TUC7AMB-STG01
Erlang configuration: Erlang/OTP 22 [erts-10.7] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:192] [hipe]
Erlang processes: 2288 used, 1048576 limit
Scheduler run queue: 1
Cluster heartbeat timeout (net_ticktime): 60
Plugins
Enabled plugin file: /etc/rabbitmq/enabled_plugins
Enabled plugins:
 * rabbitmq_prometheus
 * rabbitmq_federation_management
 * rabbitmq_shovel_management
 * rabbitmq_management
 * rabbitmq_management_agent
 * rabbitmq_shovel
 * rabbitmq_sharding
 * rabbitmq_peer_discovery_common
 * rabbitmq_federation
 * rabbitmq_web_dispatch
 * cowboy
 * amqp_client
 * amqp10_client
 * cowlib
 * amqp10_common
 * prometheus
`

And rabbitmqctl environment is at: https://slack-files.com/T307L90UD-F01BP5NC4VB-64ddaca4e5 

And an example py3 stub using pika which produces this error:

`import  models
SYS_secrets = models.SYS_secrets
import pika
SYS_rmq_nodes_arr = [{ "host": str(list(i)[0]), "port": i[list(i)[0]] }  for i in SYS_secrets['rabbitmq-nodes']]
SYS_rmq_credentials = pika.PlainCredentials(
	SYS_secrets["rabbitmq-auth"]["user"],
	SYS_secrets["rabbitmq-auth"]["pass"]
	)
rmq_random_svr = SYS_rmq_nodes_arr[0]
inputQueue = "shard.test"
def callback(ch, method, properties, body):
    print("We got a msg!! {}".format(body))
connection = pika.BlockingConnection(
    pika.ConnectionParameters(
        host=rmq_random_svr["host"],
        port=rmq_random_svr["port"],
        virtual_host=SYS_secrets["settings"]["rabbitmq-virtual-host"],
        credentials=SYS_rmq_credentials,
        socket_timeout=SYS_secrets["settings"]["rabbitmq-socket-timeout"],
    )
)
channel = connection.channel()
channel.basic_qos( prefetch_count=2000 )
channel.basic_consume(
    on_message_callback=callback,
    queue=inputQueue
    )                
print(' [*] Waiting for messages on queue: {}. To exit press CTRL+C'.format(inputQueue))
channel.start_consuming()
channel.close()
connection.close()
`

Hope this helps a bit more

**Comment by julienbonastre** [comment]
Ok, I have solved this issue now.. Somehow there was some rabbitmq bug it seems as one of the 2 nodes in cluster had not properly "taken" to enabling the rabbitmq-sharding plugin and therefore depending on which of the 2 nodes a consumer would target it would receive the errors relating to the unknown exchange type and "not found" pseudo-queue accordingly..

I simply re-ran the same `rabbitmq-plugins enable rabbitmq-sharding` on the non-working node and then all was fine and I am able to use pseudo-queues correctly now

**Comment by michaelklishin** [comment]
@julienbonastre we would appreciate if claims of "RabbitMQ bugs" were backed by logs and a set of steps to reproduce. There are relatively few reasons why enabling a plugin could fail (e.g. the plugin file is missing or cannot be read) and they should all produce visible errors in the logs and CLI tool failures (with an exit code of > 0). Claiming that "there was a bug" without any substance is simply spreading FUD in the community.

**Comment by julienbonastre** [comment]
I see, apologies,  I certainly was not aiming to generate FUD at all, rabbitmq is an excellent messaging broker...

I could try reproducing and capturing logs , I'll have to stage it in a demo env, will try to do this in next few days and raise a dedicated issue for it with detailed logs if I can reproduce it
