### ISSUE TITLE
Objective-C client: How to set clientProperties

### ISSUE THREAD

**Issue by An-uking** [rabbitmq/discussions#15]
I am designing a Flutter plugin, I want to define some clientProperties properties, but I have not found a method yet. I just found "userProvidedConnectionName"

**Comment by michaelklishin** [comment]
It is not possible at the moment, the properties are [hardcoded](https://github.com/rabbitmq/rabbitmq-objc-client/blob/5a845807072c0112168d12dfd6449867764c10a8/RMQClient/RMQHandshaker.m#L113).
