### ISSUE TITLE
Configure the RabbitMQ queue

### ISSUE THREAD

**Issue by sportmma** [rabbitmq/discussions#156]
Hello. I need to configure the RabbitMQ queue. I have pre-written configurations, but I don't know exactly where to paste them. So please help.
This is the configuration for the Magento 2.4 extension
https://github.com/macopedia/magento2-allegro
My magento installation is "bitnami" on GCP.

RABBITMQ configuration

configuration in config.php

<? php
return [
     'modules' => [
     // ...
     'Magento_Amqp' => 1, // important enable rabbitmq
     // ...
     ]
queue configuration in env.php

     'queue' => [
         'amqp' => [
             'host' => 'amqp',
             'port' => '5672',
             'user' => 'guest',
             'password' => 'guest',
         ],
     ],
consumer configuration in the env.php file

     'cron_consumers_runner' => [
         'cron_run' => true,
         'max_messages' => 20000,
         'consumers' => [
             'AllegroApiQueue'
         ]
     ]

**Comment by sportmma** [comment]
RABBITMQ configuration

configuration in config.php

<? php
return [
     'modules' => [
     // ...
     'Magento_Amqp' => 1, // important enable rabbitmq
     // ...
     ]
queue configuration in env.php

     'queue' => [
         'amqp' => [
             'host' => 'amqp',
             'port' => '5672',
             'user' => 'guest',
             'password' => 'guest',
         ],
     ],
consumer configuration in the env.php file

     'cron_consumers_runner' => [
         'cron_run' => true,
         'max_messages' => 20000,
         'consumers' => [
             'AllegroApiQueue'
         ]
     ]

**Comment by sportmma** [comment]
RABBITMQ configuration

configuration in config.php

<? php
return [
     'modules' => [
     // ...
     'Magento_Amqp' => 1, // important enable rabbitmq
     // ...
     ]
queue configuration in env.php

     'queue' => [
         'amqp' => [
             'host' => 'amqp',
             'port' => '5672',
             'user' => 'guest',
             'password' => 'guest',
         ],
     ],
consumer configuration in the env.php file

     'cron_consumers_runner' => [
         'cron_run' => true,
         'max_messages' => 20000,
         'consumers' => [
             'AllegroApiQueue'
         ]
     ]

**Comment by sportmma** [comment]
In the attachments he adds my config.php and env.php files. Maybe someone will show me where I should paste the configuration?


[env & config.zip](https://github.com/rabbitmq/discussions/files/5397142/env.config.zip)

**Comment by michaelklishin** [comment]
This is a question that will be answered much quicker by the Magento community.
