### ISSUE TITLE
Federation links are disappeared on rabbitmq restart

### ISSUE THREAD

**Issue by naveene84** [rabbitmq/discussions#16]
Hi 
We have two rabbitmq clusters with 3 nodes in each cluster. Few of the queue/exchange federation links are missing, every time we restart rabbitmq nodes as part of maintenance. Please help us to overcome this issue and let me know if you need more info regarding this issue.

rabbitmqctl --version
3.7.12
Erlang/OTP 21 [erts-10.2.4]

OS: RHEL 7.6
URI Configuration:
"uri": ["amqp://username:password@node1_ip/vhost","amqp://username:password@node2_ip/vhost","amqp://username:password@node3_ip/vhost"]

**Comment by lukebakken** [comment]
* Please use the latest RabbitMQ version. At this time it is either version `3.7.21` or `3.8.1`
* Please provide a script for recreating the federation links you're using. The script should use `rabbitmqctl`, `rabbitmqadmin` or `curl` to create the links. It's important that we are able to reproduce your environment.
* How are you restarting RabbitMQ nodes? For what purpose? "maintenance" is vague
* Please archive and **_attach_** the log files from each node when this event happens.

**Comment by michaelklishin** [comment]
Federation links won't be present if there are no policies after a restart. Depending on how those nodes are upgraded, this may end up being the case. We need full server logs and a set of steps we can use to reproduce.

**Comment by naveene84** [comment]
Hi Luke/Micheal,

Thanks for the quick reply.
> * Please provide a script for recreating the federation links you're using. The script should use `rabbitmqctl`, `rabbitmqadmin` or `curl` to create the links. It's important that we are able to reproduce your environment.
>>>>To persist the configurations explicitly, we are using load_definitions option in rabbitmq_management provided in rabbitmq.config file  to create queues, parameters, and policies. 
 {rabbitmq_management,
  [%% Preload schema definitions from a previously exported definitions file. See
   %% http://www.rabbitmq.com/management.html#load-definitions
   %%
   {load_definitions, "/etc/rabbitmq/rmqconfig.json"}

**Parameters and policy info:**
   "parameters": [{
        "vhost": "RmqVHost",
        "component": "federation-upstream",
        "name": "C2-C1-HRmqVHost-Upstream",
        "value":{
            "message-ttl":600000,
            "max-hops":1,
            "ack-mode":"on-confirm",
            "prefetch-count":50,
            "uri":["amqp://username:password@1.1.1.1/RmqVHost","amqp://username:password@1.1.1.2/RmqVHost","amqp://username:password@1.1.1.3/RmqVHost"],
            "exchange":"RMQExchange"
        }
    },{
        "vhost": "RmqVHost",
        "component": "federation-upstream-set",
        "name": "C1-U3-HRmqVHost-Upstream-set",
        "value":[{"upstream":"C2-C1-HRmqVHost-Upstream"}]
    }],
	"policies": [{
        "vhost": "RmqVHost",
        "name": "C1-U3-fed-qu-Queue1",
        "pattern": "^Queue1",
        "definition":{
            "ha-mode":"exactly",
            "ha-params":2,
            "max-length":200000,
            "queue-master-locator":"min-masters",
            "ha-sync-mode":"automatic",
            "federation-upstream-set":"C1-U3-HRmqVHost-Upstream-set"
        },
        "priority": 2,
        "apply-to": "queues"
    }]
> * How are you restarting RabbitMQ nodes? For what purpose? "maintenance" is vague
As part of software upgrade and to test site switch over use cases we will restart rabbitmq serivces frequently. we use "rabbitmqctl stop" command to stop rabbitmq service.


Federation links are disconnected properly when all nodes are stopped in upstream. But few of the federation links are not created after bringing up the upstream nodes.

**Comment by michaelklishin** [comment]
There will be no links if the queues in question are not around after restart, e.g. because they are [temporary](https://www.rabbitmq.com/queues.html#temporary-queues) or because definition import has not yet taken place. After definition import finishes — and there will be be log messages about progress — policies would match the newly declared queue(s) and links will be started.

Please do your tests with `3.7.22` and make sure that the entities to be federated and the policy are there. Without those things, no links will be started.

**Comment by michaelklishin** [comment]
Upstreams/upstream sets should also exist, of course. Both those and policies are stored in the schema database and are never transient (unless the node is a RAM one but a standalone RAM node is an impossible scenario, there has to be at least one disk node in a cluster). Queues can be and often are transient, however.

**Comment by naveene84** [comment]
Michael,

We are importing the definitions during rabbitmq initialization and all queues, policies, federation links are created successfully. (Note: We are applying policies for static queues only)

When all upstream rabbitmq nodes are stopped and started, then a few of the federation links are not re-establishing. 

All nodes in the cluster are disk nodes. 
rabbitmqctl cluster_status
Cluster status of node rabbit@gv-rmq1 ...
[{nodes,[{disc,['rabbit@rmq1',
                'rabbit@gv-rmq2',
                'rabbit@gv-rmq3']}]},

**Comment by michaelklishin** [comment]
Please reproduce with 3.7.22 and post logs that cover a timeframe from first node boot to its final state. It's also not clear to me what side is stopped, upstream or downstream.

**Comment by naveene84** [comment]
When all upstream rabbitmq nodes are stopped and started, then a few of the federation links are not re-establishing in downstream.
