### ISSUE TITLE
Web STOMP: client certificate authentication ignores certificate subject and always tries to login as guest

### ISSUE THREAD

**Issue by statsap** [rabbitmq/discussions#160]
I can't seem to get client certificate authentication working with RabbitMQ 3.8.8 or 3.8.9 on Windows. It keeps attempting to login as guest even though I'm logging in with certificate for different user. It fails because I've deleted the guest account for security.

I get the following error logged:
```
2020-11-04 16:17:28.123 [error] <0.1227.0> STOMP error frame sent:
Message: "Bad CONNECT"
Detail: "Access refused for user 'guest'\n"
Server private detail: none
```

This is strange because I am not setting any login or passcode STOMP headers, I don't have a `stomp.default_user` or `stomp.default_pass` set in my rabbitmq.conf, and the client certificate's CN in the subject is not guest (it's user1 and the user exists). I'm using the Spring Boot Web STOMP client library.

Here are the relevant settings from my rabbitmq.conf:
```
ssl_cert_login_from = common_name
ssl_options.verify = verify_peer
ssl_options.fail_if_no_peer_cert = true
stomp.ssl_cert_login = true
web_stomp.ssl.port = 15673
web_stomp.ssl.cacertfile = ...
web_stomp.ssl.certfile = ...
web_stomp.ssl.keyfile = ...
```

Something odd I noticed is the schema in the GitHub repository does not match what is shipped in Rabbit 3.8.8/3.8.9:
- The [rabbitmq_web_stomp.schema](https://github.com/rabbitmq/rabbitmq-web-stomp/blob/master/priv/schema/rabbitmq_web_stomp.schema) file in GitHub defines a [`web_stomp.use_http_auth`](https://github.com/rabbitmq/rabbitmq-web-stomp/blob/6eff6443fad8f3ec7481c18f63510782b7d981ba/priv/schema/rabbitmq_web_stomp.schema#L35) value
- However if you open up `rabbitmq_web_stomp-3.8.9.ez` in the RabbitMQ server's plugins directory and view the `/priv/schema/rabbitmq_web_stomp.schema` file, that `web_stomp.use_http_auth` value doesn't appear anywhere.

I'm not sure if this is related to my issue or not.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.

**Comment by michaelklishin** [comment]
My guess from a quick look at the code is that you have to configure the "login from" part for STOMP. Web STOMP doesn't have a separate setting. If/what value is extracted from the certificate is controlled by STOMP plugin state.

Why it is the case? Because there wasn't virtually any interest in x.509 certificate-based authentication for Web STOMP or Web MQTT up until this month, and because this feature and the STOMP plugin is much older than Web STOMP.

It's a good question whether Web STOMP or Web MQTT should reinvent this x.509 certificate authentication settings.
Web STOMP can be used differently from STOMP, and it can get confusing both ways :(

**Comment by michaelklishin** [comment]
`web_stomp.use_http_auth` is not related to x.509 authentication at all. You haven't mentioned what branch you were looking at. RabbitMQ 3.8 releases are **not** produced off of master but `v3.8.x` instead. `master` is used for RabbitMQ 3.9 development.

**Comment by michaelklishin** [comment]
It's something that deserves a doc guide section. Filed an issue above.
