### ISSUE TITLE
RabbitMQ Federation blocking

### ISSUE THREAD

**Issue by Tony-S241** [rabbitmq/discussions#167]
I'm having trouble with a few of my federation upstreams. They seem to be frequently closing connections and then timing out when reconnecting. I'm running two 3 node clusters on ubuntu 16.04. I'm using Rabbitmq version 3.8.9 with erlang 23.1.5. My federation upstream is configured as follows: 
uri: amqp://username:password@rabbit01/vhost
reconnect delay: 10s
ack mode: on-confirm
trust user-id: true
exchange: exchange01
Max hops: 1
Policy:
	federation-upstream-set: all
	ha-mode: all
	ha-sync-mode: manual (edited) 
	
The error messages received are error, timeout and 404 not found, no exchange in vhost. The no exchange error is strange because at the end it has a letter A or B and the exchange that exists has one of those two letters. I've also seen in packet captures, something about connection.blocked and authentication failures. I've already confirmed the credentials for the federation upstream in both clusters though.

In the RabbitMQ logs, i'm seeing this: 2020-12-10 09:18:07.307 [error] <0.8665.0> Channel error on connection <0.8657.0> (10.51.0.82:35709 -> 10.150.0.97:5672, vhost: 'vhost', user: 'federation'), channel 1:
operation queue.bind caused a channel exception not_found: no exchange 'federation: federation.exchange -> rabbit@rabbit01 B' in vhost 'vhost'

and

2020-12-10 00:02:28.402 [error] <0.22507.8> Federation link could not create a disposable (one-off) connection due to an error exit: {timeout,{gen_server,call,[<0.24137.8>,connect,60000]}}
2020-12-10 00:02:28.430 [error] <0.22507.8> ** Generic server <0.22507.8> terminating
** Last message in was {#Ref<0.946068889.4176216066.67625>,{error,timeout}}
** When Server state == {state,{upstream,[{encrypted,<<"oER5aDiFKTeblzh3++WQHKdIYPAx/ScrGkPem5SqFCONjAxyVvkqhZhFM7xxv9m2eXJg35EvMt/fV/2MsVewrf/vD0YO0b8h0sK9vgSFMRw=">>},{encrypted,<<"a1AhbsDk1jlDLvw7MNIhnBeAm9LH85yPdujnGWireLyl8e0d4L3bz3y5qrlOR1kuJC1Lox2rrodDjdYyPthUMD0vgIg65QQ/tqPYK6Fi0y4=">>},{encrypted,<<"7zAjMw11Gasjex7E/FSoACpRDO3Else+VQ8TY+orvL7vBFqRtlTLaifFmEfeF/+K9ZNDN5BhFmj5+S5a7cmSwm71gD9E9DEc3lwVO4Zz8S4=">>}],<<".federation.exchange">>,<<".federation.exchange">>,<<"federation-link-Federation__DV-US1">>,1000,1,10,none,none,true,'on-confirm',<<".federation">>,<<"Federation__DV-US1">>,false,default},{upstream_params,{encrypted,<<"racVSc/gPkqmimu7Q7TUzC677lXXl00obkb98iAGp3D9fA969oAsmxobcZa860UnCePTZLbWIXouBBBFqRm1gehemV1JAL94AroT0SgxmEk=">>},{amqp_params_network,<<"_federation">>,{encrypted,<<"k49dlrHaQ9ABVnZNr9O6YS2RDDV+t2HG+dbp8XzwrOqOMQtf9UiqaBxZkDypsoSh">>},<<"">>,"us1-rmq-d02",undefined,2047,0,10,60000,none,[#Fun<amqp_uri.12.131604370>,#Fun<amqp_uri.12.131604370>],[],[]},{exchange,{resource,<<"">>,exchange,<<".federation.exchange">>},topic,true,false,false,[],[{federation,[{{<<"Federation__DV-US1">>,<<".federation.exchange">>},<<"B">>},{{<<"Federation__DV-US2">>,<<".federation.exchange">>},<<"B">>}]}],[{vhost,<<"">>},{name,<<".federation">>},{pattern,<<"^.federation\\.">>},{'apply-to',<<"all">>},{definition,[{<<"federation-upstream-set">>,<<"all">>},{<<"ha-mode">>,<<"all">>},{<<"ha-sync-mode">>,<<"manual">>}]},{priority,0}],undefined,{[],[rabbit_federation_exchange]},#{user => <<"rmq-tf-dev">>}},<<"amqp://us1-rmq-d02/">>,[{<<"uri">>,longstr,<<"amqp://us1-rmq-d02/">>},{<<"exchange">>,longstr,<<".federation.exchange">>}]},<<"rabbit@US1-RMQ-D01.plex.com">>,<0.22522.8>,<0.22531.8>,<0.22535.8>,<<"amq.ctag--th6zLxwyt6ZC1bnaYHEQg">>,<<"federation: .federation.exchange -> rabbit@DV-RMQ-D01.plex.com">>,<<"federation: .federatio...">>,...}
** Reason for termination == 
** {unexpected_info,{#Ref<0.946068889.4176216066.67625>,{error,timeout}}}
2020-12-10 00:02:28.430 [info] <0.22507.8> [{initial_call,{rabbit_federation_exchange_link,init,['Argument__1']}},{pid,<0.22507.8>},{registered_name,[]},{error_info,{exit,{unexpected_info,{#Ref<0.946068889.4176216066.67625>,{error,timeout}}},[{gen_server2,terminate,3,[{file,"src/gen_server2.erl"},{line,1183}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}},{ancestors,[<0.10017.0>,<0.4352.0>,rabbit_federation_exchange_link_sup_sup,rabbit_federation_sup,rabbit_sup,<0.281.0>]},{message_queue_len,4},{messages,[{'DOWN',#Ref<0.946068889.4175953922.204545>,process,<0.22516.8>,normal},{'DOWN',#Ref<0.946068889.4174905345.141726>,process,<0.22531.8>,normal},{'DOWN',#Ref<0.946068889.4174905345.141746>,process,<0.22535.8>,normal},{'DOWN',#Ref<0.946068889.4174905345.141747>,process,<0.22535.8>,normal}]},{links,[<0.10017.0>]},{dictionary,[{rand_seed,{#{bits => 58,jump => #Fun<rand.3.47293030>,next => #Fun<rand.0.47293030>,type => exsss,uniform => #Fun<rand.1.47293030>,uniform_n => #Fun<rand.2.47293030>},[230252298850391189|62299441385715918]}},{gen_server_call_timeout,60000}]},{trap_exit,true},{status,running},{heap_size,2586},{stack_size,28},{reductions,88001}], []
2020-12-10 00:02:28.430 [error] <0.22507.8> CRASH REPORT Process <0.22507.8> with 0 neighbours exited with reason: {unexpected_info,{#Ref<0.946068889.4176216066.67625>,{error,timeout}}} in gen_server2:terminate/3 line 1183
2020-12-10 00:02:28.431 [error] <0.10017.0> Supervisor {<0.10017.0>,rabbit_federation_link_sup} had child {upstream,[{encrypted,<<"oER5aDiFKTeblzh3++WQHKdIYPAx/ScrGkPem5SqFCONjAxyVvkqhZhFM7xxv9m2eXJg35EvMt/fV/2MsVewrf/vD0YO0b8h0sK9vgSFMRw=">>},
           {encrypted,<<"a1AhbsDk1jlDLvw7MNIhnBeAm9LH85yPdujnGWireLyl8e0d4L3bz3y5qrlOR1kuJC1Lox2rrodDjdYyPthUMD0vgIg65QQ/tqPYK6Fi0y4=">>},
           {encrypted,<<"7zAjMw11Gasjex7E/FSoACpRDO3Else+VQ8TY+orvL7vBFqRtlTLaifFmEfeF/+K9ZNDN5BhFmj5+S5a7cmSwm71gD9E9DEc3lwVO4Zz8S4=">>}],
          <<"federation.exchange">>,<<".federation.exchange">>,
          <<"federation-link-Federation_DV-US1">>,1000,1,10,none,none,
          true,'on-confirm',<<".federation">>,<<"Federation_DV-US1">>,
          false,default} started with rabbit_federation_exchange_link:start_link({{upstream,[{encrypted,<<"oER5aDiFKTeblzh3++WQHKdIYPAx/ScrGkPem5SqFCONjAxyVvkqhZhFM7xxv9m2eXJg35...">>},...],...},...}) at <0.22507.8> exit with reason {unexpected_info,{#Ref<0.946068889.4176216066.67625>,{error,timeout}}} in context child_terminated

**Comment by lukebakken** [comment]
There's not enough information here to assist.

A good place to start is to run this script on all nodes in both clusters, then attach the generated archives to your next comment:

https://github.com/rabbitmq/support-tools/blob/master/scripts/rabbitmq-collect-env

In addition, read this document and provide more information: https://github.com/rabbitmq/support-tools/blob/master/docs/Reporting_RabbitMQ_Issues.md#general-questions

For instance, it would be great to know if these environments worked without issue for a time, and then exhibited this problem.

**Comment by tsawanplex** [comment]
Hi Luke, thank you for your help. These are new clusters. These same clusters have federation upstreams to clusters in other data centers that work with identical setup. The issue is re-occuring frequently and only between these two clusters. I have ran the script on all nodes, is there a way for me to privately share this with you?

**Comment by lukebakken** [comment]
> These same clusters have federation upstreams to clusters in other data centers that work with identical setup

This points to an environment problem, not RabbitMQ, wouldn't you agree? I can still check the logs but given that fact I suggest checking for network connectivity issues, firewalls, etc - anything that could sever TCP connections.

What is different about the environments that do not have this problem vs those that do?

You can contact me personally via the email address shared on my GitHub profile. Rather than send large files over email, upload them to something like google drive or dropbox and share them that way.

**Comment by Tony-S241** [comment]
Thanks, I have shared a link to the files via dropbox. I do agree that it could be environment however I haven't been able to find any network issues. I'm not able to reproduce any connectivity errors outside of RMQ federations. The RMQ clusters that these new ones are replacing are in the same environment and federation TCP connections are not failing.

The environments are setup exactly the same. The only difference between them is what datacenter they are located in. 

I'm actively reviewing packet captures and see a lot of this:

basic.nackt..consumer_cancel_notifyt..connection.blockedt..consumer_prioritiest..authentication_failure_closet..per_consumer_qost..direct_reply_tot..cluster_nameS....rabbit@rabbitnode.

I've confirmed that the account used for federation works with the credentials supplied in both rabbit clusters. Not sure what to make of it.

**Comment by lukebakken** [comment]
>basic.nackt..consumer_cancel_notifyt..connection.blockedt..consumer_prioritiest..authentication_failure_closet..per_consumer_qost..direct_reply_tot..cluster_nameS....rabbit@rabbitnode.

That looks like capability negotiation during connection establishment. If you see a lot of them it means AMQP connections are happening repeatedly, either Federation or your applications. Connection churn is a _bad thing_.

**Comment by lukebakken** [comment]
You have one cluster that won't start due to mnesia errors:

[mnesia-errors.txt](https://github.com/rabbitmq/discussions/files/5682089/mnesia-errors.txt)

It appears that RabbitMQ is in a restart loop due to this.

https://www.rabbitmq.com/partitions.html#recovering

**Comment by Tony-S241** [comment]
Thank you for reviewing the logs. Those errors are from 3 months ago. We dont have any partitions or mnesia errors currently. I’ll keep digging on my side.
