### ISSUE TITLE
How do i find out the client who consumes the queue

### ISSUE THREAD

**Issue by ishamfazal** [rabbitmq/discussions#17]
Hi, can anyone help me out on how to find out the client nor the consumer who consumes the queue.
is there something like signalR connectionId for each client. how ever the reason behind this is i need to send messages to a specific client on a particular queue. how do i achieve this. i believe there should be a connectionId for each client. my application is built on c# .net core project.
this is my architecture 
![image](https://user-images.githubusercontent.com/11960696/69699507-87405080-1101-11ea-91ae-d0e35274e9b4.png)

however, my task is to find out who sent the message and respond back to that client.

**Comment by michaelklishin** [comment]
Consider posting questions to the RabbitMQ mailing list, `rabbitmq-users`, in the future.

Your publishers need to include relevant information into the message. See [tutorial 6](http://www.rabbitmq.com/getstarted.html) which demonstrates the idea. Obviously you can include more information as needed into a set of [available message properties](https://www.rabbitmq.com/publishers.html#message-properties) or headers. Note that this is protocol-dependent, e.g. AMQP 0-9-1, STOMP and AMQP 1.0 are quite extensible but MQTT is not.

Alternatively, you can set up your routing topology in a way that messages with a specific routing key reach only a specific queue, which only a specific consumer or set of [consumers](https://www.rabbitmq.com/consumers.html) consume from.
