### ISSUE TITLE
Exchnage doesn't work after 2,3 days

### ISSUE THREAD

**Issue by Deem97** [rabbitmq/discussions#173]
I used the rabbitmq delayed message plugin with the below implementation.

$this->getChannel()->exchange_declare(
    'ohrm_delayed_msg_queue_exchange',
    'x-delayed-message', false,true,false,false,
    ['x-delayed-type' => ['S', 'topic']]);

But there is a problem when we publish messages it works but when we publish the messages after 2,3 days the messages are coming to the exchange but not going to the correct queue.

**Comment by michaelklishin** [comment]
I'm afraid we cannot suggest much with this amount of information. This plugin has plenty of [documented limitations](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/#limitations). Nothing in this plugin is tied to the value that would be comparable to `2.3` or 2-3 days. It can delay for up to ~ 49 days and exchanges do not have the concept of a TTL.

You claim that "messages are not going to the correct queue". Are they routed anywhere at all? How many messages are delayed according to the exchange page in the management UI? Are any cluster nodes restarted in this time period? This exchange does not replicate the messages it delays, as covered in the Limitations section of the docs.
