### ISSUE TITLE
Federation links are not seen when rabbitmq is restarted

### ISSUE THREAD

**Issue by vkuser-web** [rabbitmq/discussions#174]
I have a federation (exchange federation) setup between two clusters with 2 nodes in each cluster. The federation is working fine and federation status displays the link. If rabbitmq is restarted on the downstream where the federation commands are invoked, the federation status output is blank and does not display any federation link.  I verified that the upstream sets, upstream and policy are present after rabbitmq server restart.  This behavior is seen on each restart and easily reproducible.

This issue  is similar to https://github.com/rabbitmq/discussions/issues/16
**If a recreate (delete and create) the policy, the links are visible again.**

After restart federation status. 
rabbitmqctl federation_status
Listing federation links on node rabbit@mgmt1...
[]

rabbitmqctl --version
3.8.1
Erlang 22.0.6

OS: Oracle Linux 8 

Commands used to setup federation:
1)Create a upstream-set:
rabbitmqctl set_parameter federation-upstream-set demo-set '[{"upstream": "upstream-one"}]'
2)Declare exchange:
rabbitmqadmin declare exchange name=demo-fedex-ex1 type=headers durable=true
3)Create upstream:
rabbitmqctl set_parameter federation-upstream upstream-one "{'uri':'amqp://host-name','expires':3600000}"
4)Set Policy
rabbitmqctl set_policy --apply-to exchanges demo-policy ".*fedex-ex1" "{'federation-upstream-set':'demo-set'}"

Please let me know if more data is needed.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.

**Comment by michaelklishin** [comment]
By far the most common reason is that no exchanges (or queues) are matched by the federation policy. Only one policy is in effect at a time (policies are not merged). Consult logs for more clues and upgrade to 3.8.16. RabbitMQ 3.8.1 is a cool version from 2019.
