### ISSUE TITLE
How to mirror  between the  two cluster？

### ISSUE THREAD

**Issue by jianghenglz** [rabbitmq/discussions#175]

**Comment by michaelklishin** [comment]
It depends on what you mean by "mirror". The question is really terse.

For hot standbys, see [exchange federation](https://www.rabbitmq.com/federation.html). For moving data around, see [Shovel](https://www.rabbitmq.com/shovel.html). Queue federation is a third option that allows data to be moved where local consumers are.

More options will be available in Tanzu RabbitMQ (commercial edition) later this year.
