### ISSUE TITLE
JWT Authorization with RabbitMQ in MicroServices Architecture General

### ISSUE THREAD

**Issue by ardaorkin** [rabbitmq/discussions#176]
Hello.

I need some support about a scenario I am currently working on. Any help would be appreciated. So here is what I’m involved:

I have an application that uses NodeJS on the backend and ReactJS on the frontend. This application has microservice architecture. I use Apollo Server to provide communication between backend services and ReactJS. All services use RabbitMQ and they have their own exchange. One of these services is the user authorization and authentication service which has also used AMQP to deliver and send messages. So when a user tries to log in, Apollo Server receives the credentials, sends them to the message broker, and a consumer in the user authentication service consumes the message which includes the user credentials, produces a JSONWebToken, and then sends the token to the message broker. A subscriber in the Apollo Client which is in ReactJS handles the token and makes the user login. So here is what I am wondering:

Is this scenario a good and preferred scenario to use in the user authentication - authorization process?
What if 1000 users make the same request at the same time with different internet connection speeds? Could the Apollo Client receive the wrong token? I mean let’s imagine 2 users make a request to login, Apollo Server receives them, sends the credentials which are request includes to MQ, user auth service consume the credentials, reproduce token, send them to MQ. Is it possible that UserA receives UserB’s token?
Best regards.

**Comment by michaelklishin** [comment]
Authentication can be done this way but in most systems, authentication is an inherently synchronous operation: you don't proceed with anything else until it succeeds. By making this a multi-service, multi-message interaction over an inherently asynchronous channel (RabbitMQ queues), you are introducing a fair amount of complexity. We can't know if the complexity is worth the gain.

We cannot provide much guidance on the Apollo server or what it does. There certainly are ways to do [request/reply style communication](https://www.rabbitmq.com/getstarted.html) (see tutorial 6) with concurrent clients. They have to use [Direct Reply-to](https://www.rabbitmq.com/direct-reply-to.html) on separate channels (or connections, which happens naturally in a realistic system) or individual queues for responses. Any limitations here would come from your own code/service or how this Apollo server uses RabbitMQ, which our teams unfortunately knows nothing about.

**Comment by ardaorkin** [comment]
Thank you so much for the clarity.
