### ISSUE TITLE
Need help having some payload not string issue when sending nested JSON to Rabbit MQ 

### ISSUE THREAD

**Issue by jayber01** [rabbitmq/discussions#177]
"error":"bad_request","reason":"payload_not_string"}

this is my test JSON message 

{ "properties": {
"content_type": "application/json"},
"routing_key": "info",
"payload_encoding": "string",
"payload": {
"records":{
"name":"testname"}}}

**Comment by michaelklishin** [comment]
There isn't much context here but if you are trying to publish over the HTTP API, I have two pieces of advice:

 * Don't. We never recommend publishing this way. It's extremely inefficient compared to using regular messaging protocol clients
 * If you absolutely have to, use existing HTTP API clients (including [`rabbitmqadmin`](https://github.com/rabbitmq/rabbitmq-server/blob/master/deps/rabbitmq_management/bin/rabbitmqadmin)) or at least see what they do

**Comment by jayber01** [comment]
hi thank you I got the solution now im using yajl with escape solidus in as400 server via httpapi all working now
