### ISSUE TITLE
AMQJS0008I Socket closed.

### ISSUE THREAD

**Issue by heppytt** [rabbitmq/discussions#178]
![image](https://user-images.githubusercontent.com/17058423/124382836-f9c0db80-dcfb-11eb-8369-603b0f6ab8a4.png)
I use mqttws31.js connect web-mqtt 
mqttws31.js return AMQJS0008I Socket closed. 
I dont kown why?

**Comment by michaelklishin** [comment]
We can't know with the amount of information provided. It can be a firewall or you may be trying to [connect from a remote host using default user credentials](https://www.rabbitmq.com/access-control.html#loopback-users), which is prohibited.

See [server logs](https://www.rabbitmq.com/logging.html#logged-events) for clues and [Troubleshooting Networking](https://www.rabbitmq.com/troubleshooting-networking.html) for a methodology our team recommends in such cases.
