### ISSUE TITLE
How to pin a Rabbitmq version on Ubuntu?

### ISSUE THREAD

**Issue by rjonala** [rabbitmq/discussions#179]
I am using PackageCloud package to install Rabbitmq using Ansible. When I installed using PackageCloud, 3.8.19 was installed on few servers and 3.9.1 was installed on other servers. But I am trying to pin Rabbitmq version so that all Rabbitmq servers in all environments have the same version 3.8.19.

I added a file too `/etc/apt/preferences.d/rabbitmq` with the content

```
Package: rabbitmq-server
Pin: version 1:3.8.19
Pin-Priority: 1000
```
as mentioned in RMQ documentation but it still installs the latest version 3.9.3 instead of 3.8.19.

I have also tried installing manually without Ansible with no luck. Can someone please help me fix the issue? Thank you :)

**Comment by Gsantomaggio** [comment]
After the configured the repositories you should have something like:
```shell
sudo apt-cache policy rabbitmq-server
rabbitmq-server:
  Installed: (none)
  Candidate: 3.9.3-1
  Version table:
     3.9.3-1 500
        500 https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu focal/main amd64 Packages
     3.9.2-1 500
        500 https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu focal/main amd64 Packages
     3.9.1-1 500
        500 https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu focal/main amd64 Packages
     3.9.0-1 500
        500 https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu focal/main amd64 Packages
     3.8.21-1 500
        500 https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu focal/main amd64 Packages

```

then you can pin the version using:

```shell
sudo cat /etc/apt/preferences.d/rabbitmq
Package: rabbitmq-server
Pin: version  3.8.19-1
Pin-Priority: 1000
```

now the Candidate is the right one:
```shell
 sudo apt-cache policy rabbitmq-server
rabbitmq-server:
  Installed: (none)
  Candidate: 3.8.19-1
```

just install it and then:
```shell
rabbitmqctl status
Status of node rabbit@node0 ...
Runtime

OS PID: 18690
OS: Linux
Uptime (seconds): 15
Is under maintenance?: false
RabbitMQ version: 3.8.19

```

**Comment by michaelklishin** [comment]
The -1 part is the Debian epoch (package revision if you like). You can pin to any epoch using something like `Pin: version 3.8.19*` but I haven't tried it.

It may be that some `apt` versions or Debian package hosting providers implicitly assume the epoch to be `1` if not specified. Anyhow,
we'd be happy to update the docs.

**Comment by rjonala** [comment]
Thanks @Gsantomaggio that worked for rabbitmq-server. This is really helpful. It would be great if the official RMQ documentation is updated accordingly.

Also, if I want to pin erlang, how would that be? I have tried the following but didn't work
**/etc/apt/preferences.d/erlang**
      ```
Package: erlang*
      Pin: version 1:23.3.1-1
      Pin-Priority: 1000
```

When I ran **sudo apt-cache policy erlang**, it gave me

```
erlang:
  Installed: (none)
  Candidate: 1:24.0.5-1rmq1ppa1~ubuntu18.04.1
  Version table:
     1:24.0.5-1rmq1ppa1~ubuntu18.04.1 500
        500 http://ppa.launchpad.net/rabbitmq/rabbitmq-erlang/ubuntu bionic/main amd64 Packages
        500 http://ppa.launchpad.net/rabbitmq/rabbitmq-erlang/ubuntu bionic/main i386 Packages
     1:23.3.4-1rmq1ppa1~ubuntu18.04.1 500
        500 http://ppa.launchpad.net/rabbitmq/rabbitmq-erlang/ubuntu bionic/main amd64 Packages
        500 http://ppa.launchpad.net/rabbitmq/rabbitmq-erlang/ubuntu bionic/main i386 Packages
     1:22.0.7+dfsg-1build1~ubuntu18.04.1 100
        100 http://us.archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages
        100 http://us.archive.ubuntu.com/ubuntu bionic-backports/universe i386 Packages
     1:20.2.2+dfsg-1ubuntu2 500
        500 http://us.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu bionic/universe i386 Packages
```
Please let me know the issue with my **/etc/apt/preferences.d/erlang** file. Thank you :)
