### ISSUE TITLE
status error in my Running mirror cluster with two nodes

### ISSUE THREAD

**Issue by zhangfengsd** [rabbitmq/discussions#18]
Thank you for using RabbitMQ.

**STOP NOW AND READ THIS** BEFORE OPENING A NEW ISSUE ON GITHUB

Unless you are CERTAIN you have found a reproducible problem in RabbitMQ or
have a **specific, actionable** suggestion for our team, you must first ask
your question or discuss your suspected issue on the mailing list:

https://groups.google.com/forum/#!forum/rabbitmq-users

Team RabbitMQ does not use GitHub issues for discussions, investigations, root
cause analysis and so on.

Please take the time to read the CONTRIBUTING.md document for instructions on
how to effectively ask a question or report a suspected issue:

https://github.com/rabbitmq/rabbitmq-server/blob/master/CONTRIBUTING.md#github-issues

Following these rules **will save time** for both you and RabbitMQ's maintainers.

Thank you.

**Comment by michaelklishin** [comment]
According to the message from `rabbitmqctl`, the node or an [intermediary](https://www.rabbitmq.com/networking.html#intermediaries) closed TCP connection before CLI tools could [authenticate with the node](https://www.rabbitmq.com/cli.html#erlang-cookie). The node uses port `25677` for inter-node traffic, perhaps its worth investigating if that port is [open](https://www.rabbitmq.com/networking.html#ports).

RabbitMQ has a doc guide that explains how to [investigate network connectivity issues quicker](https://www.rabbitmq.com/troubleshooting-networking.html). I cannot know if this is a genuine connection interruption, a [proxy effect](https://www.rabbitmq.com/networking.html#intermediaries) or the port is firewalled off entirely. As with any question, see server logs for possible additional clues and consider taking a traffic capture. It is **very unlikely** to be an issue with the Erlang cookie (shared secret) as that would result in a more specific error message.

On an unrelated note, you are [20 patch releases behind](https://www.rabbitmq.com/changelog.html) even in the 3.7.x series.
