### ISSUE TITLE
How to add the Set-Cookie 'Secure' attribute in rabbitmq management UI pages response header?

### ISSUE THREAD

**Issue by cloudstrife3000** [rabbitmq/discussions#184]
Hi

Our Vulnerability Assessment reported missing  'Secure' attribue (Encrypted Session (SSL) Cookie) in management UI's Set-Cookie response header. 
So how can we fix this? Thanks.

For example : 
Set-Cookie:  Cookie Id; Secure

**Comment by michaelklishin** [comment]
RabbitMQ allows for setting [some security-related headers](https://rabbitmq.com/management.html) (HSTS, CSP, and so on) but not this one. You can use a reverse proxy of your choosing in front of the HTTP API, such as Nginx or HAproxy, and set arbitrary response HTTP headers that way.
