### ISSUE TITLE
federation links disappear after rmq restart

### ISSUE THREAD

**Issue by kotyara85** [rabbitmq/discussions#185]
rmq: rabbitmq:3.9.8-management-alpine
queues and exchanges are available on the restart
the only way to make federation to work again is to remove policy and recreate it
screenshots attache
<img width="793" alt="Screen Shot 2021-11-06 at 10 47 26 AM" src="https://user-images.githubusercontent.com/10145395/140619070-2494dbde-aeae-4fe1-b686-5a3afd54ae95.png">
<img width="900" alt="Screen Shot 2021-11-06 at 10 47 51 AM" src="https://user-images.githubusercontent.com/10145395/140619071-c6546cf5-b60f-4c94-a107-71b2e7bc1016.png">
<img width="679" alt="Screen Shot 2021-11-06 at 10 47 38 AM" src="https://user-images.githubusercontent.com/10145395/140619073-5caab389-8912-4c2f-a4a5-c76091e2f34b.png">

<img width="1300" alt="Screen Shot 2021-11-06 at 10 50 16 AM" src="https://user-images.githubusercontent.com/10145395/140619067-1e5e1411-2415-4c31-b2ff-221b83c7be71.png">
d

**Comment by michaelklishin** [comment]
Please share logs and policy/runtime parameter definitions. Screenshots are of very little use.

Links will only be started if there are queues or exchange that match a federation policy, said policy has the highest priority and upstreams are configured correctly.

Federation will log a fair amount of activity at debug level. We do not guess in this community.
