### ISSUE TITLE
Looking for stable RMQ version

### ISSUE THREAD

**Issue by t4teju60** [rabbitmq/discussions#186]
We have our RMQ cluster running with 3.8.11 we would like to upgrade to 3.9.x, can anyone confirm the stable version from 3.9.x.

**Comment by Gsantomaggio** [comment]
here you can find the last stable:

https://www.rabbitmq.com/download.html 
```
The latest release of RabbitMQ is xxxx 
```

**Comment by t4teju60** [comment]
Anyone using version 3.9.6 or 3.9.8 for a large 14 node cluster, if so do you see any issues with these versions. where can i find the user reviews for a particular version i am trying to avoid a situation where will upgrade to a version then spent lot of time on fixing the issues, if someone has already tried and can advise it would save lot of time.
