### ISSUE TITLE
RabbitMQ log error: handle.exe output did not contain a line beginning with '  File '

### ISSUE THREAD

**Issue by ngsuityan** [rabbitmq/discussions#188]
Hello, currently I am using rabbitmq v3.8.8 and just followed the procedures to add inside the handle.exe into the environment setting of the window system. After adding the handle.exe, this error is appear in the log file of rabbitMQ:

```
handle.exe output did not contain a line beginning with '  File ', unable to determine used file descriptor count: "\r\nNthandle v4.22 - Handle viewer\r\nCopyright (C) 1997-2019 Mark Russinovich\r\nSysinternals - www.sysinternals.com\r\n\r\nHandle type summary:\r\r\n  ALPC Port       : 1\r\r\n  Desktop         : 1\r\r\n  Directory       : 2\r\r\n  EtwRegistration : 106\r\r\n  Event           : 184\r\r\n  Event           : 189\r\r\n  Event           : 14\r\r\n  IoCompletion    : 5\r\r\n  IRTimer         : 6\r\r\n  Mutant          : 1\r\r\n  Process         : 4\r\r\n  Section         : 1\r\r\n  Semaphore       : 6\r\r\n  Thread          : 78\r\r\n  TpWorkerFactory : 3\r\r\n  WaitCompletionPacket: 8\r\r\n  WindowStation   : 2\r\r\nTotal handles: 611\r\r\n"
```

somethime this message will floor the log file, however it don have tutorial that teach to fix this errors, anybody has this experinces an know how to fix it?

**Comment by michaelklishin** [comment]
The node fails to parse the following output:

```
Nthandle v4.22 - Handle viewer
Copyright (C) 1997-2019 Mark Russinovich
Sysinternals - www.sysinternals.com

Handle type summary:
  ALPC Port       : 1
  Desktop         : 1
  Directory       : 2
  EtwRegistration : 106
  Event           : 184
  Event           : 189
  Event           : 14
  IoCompletion    : 5
  IRTimer         : 6
  Mutant          : 1
  Process         : 4
  Section         : 1
  Semaphore       : 6
  Thread          : 78
  TpWorkerFactory : 3
  WaitCompletionPacket: 8
  WindowStation   : 2
Total handles: 611

```

Therefore it cannot compute how many file handles the node uses. This is harmless if the node only uses a few handles but dangerous if the number of open files and concurrent connections grows, as the node would never find out it'd hit a limit. Not sure if Windows has one, other operating systems do.

I cannot immediately tell why but this parser has been revisited at least in 3.9. 3.8.8 is [from 2020](https://rabbitmq.com/changelog.html) 3.8 is [out of general support](https://rabbitmq.com/versions.html). So please start with upgrading.

**Comment by michaelklishin** [comment]
The very first line, `Nthandle`, seems weird. Should it be just `handle`, or the output has changed over time? Or I misremember what it looked like a few years ago. Oh well.

**Comment by ngsuityan** [comment]
@michaelklishin  what means by you for the system language? how to switch to an English variant and compare the behavior? Any link that provide the procedure to fix this problem?

**Comment by michaelklishin** [comment]
@ngsuityan every OS lets you configure a language it uses for its UI, error messages, and many tool may use for output. A quick Google search suggests [it is done via the [Clock, Language and Region setting pane](https://answers.microsoft.com/en-us/site/completesignin?silent=True&returnUrl=https%3A%2F%2Fanswers.microsoft.com%2Fen-us%2Fsurface%2Fforum%2Fall%2Fhow-to-change-system-locale-in-windows-10-the%2Fd7826ef0-13cd-43ea-8e01-2846d813dfed&wa=wsignin1.0).

We explained what our best hypothesis is right now. Please help us test it by explaining what locale is used and trying an English locale to compare. Upgrading RabbitMQ to a supported version is a good idea but we cannot guarantee that
the issue will go away, it affects a very small % of installations and we don't know what the difference is. This is open source software that you get for free, so consider contributing to it by helping us understand that.

**Comment by lukebakken** [comment]
The following image was provided in slack - https://rabbitmq.slack.com/archives/C1EDN83PA/p1648519977046789

Note that the issue happens about every 12 to 16 minutes.

![image](https://user-images.githubusercontent.com/514926/161057860-5f0e1cdd-4dc0-4f67-a4bf-014a432d39c9.png)

**Comment by michaelklishin** [comment]
So it's not even a particular environment, it's a subset of runs (the disk monitor runs every 30s or so these days?)

**Comment by ngsuityan** [comment]
is that meaning that the language i use in the thingsboard to provide the
output message? I use javascript apply inside thingsboard to display the
live wireless data detected

Data~>rabbitmq~>thingsboard

Michael Klishin ***@***.***> 于 2022年3月31日周四 下午7:20写道：

**Comment by michaelklishin** [comment]
@ngsuityan please read what we are asking in full. It's the *natural human* language your OS interface uses (English, Spanish, Mandarin, Russian, what have you). Our best guess is that it changes the output of `handle.exe`. What programming languages your applications use is not relevant here.

Although if this happens every 15-16 minutes, so every 180 runs, it must be something else 😢

**Comment by ngsuityan** [comment]
sorry if any inconvenient，the os interfaces using the english language

Michael Klishin ***@***.***> 于 2022年3月31日周四 下午11:05写道：

**Comment by ngsuityan** [comment]
> @ngsuityan please read what we are asking in full. It's the _natural human_ language your OS interface uses (English, Spanish, Mandarin, Russian, what have you). Our best guess is that it changes the output of `handle.exe`. What programming languages your applications use is not relevant here.
> 
> Although if this happens every 15-16 minutes, so every 180 runs, it must be something else cry

![image](https://user-images.githubusercontent.com/83693028/161483384-a036893c-c562-4f55-ac37-34d8ac2e6d93.png)
 the locale language is english(Unite States)

**Comment by ngsuityan** [comment]
@michaelklishin @lukebakken  Is that means no solution to fix this problem until the further update of the rabbitMQ? Rather than official website of rabbitMQ, any tutorial video of procedure that can help me learn to upgarde the version of rabbitMQ v3.8.x to v3.9.x?

**Comment by michaelklishin** [comment]
@ngsuityan we don't know why `handle.exe` output is different every Nth run and that tool is not open source. So we don't know how to reproduce and what can potentially be changed in RabbitMQ. If this only happens every Nth run, it should be harmless since disk monitoring data would be available to the node most of the time.

**Comment by ngsuityan** [comment]
Ok, thanks.

Michael Klishin ***@***.***> 于 2022年4月5日周二 下午12:15写道：

**Comment by Manvendra11** [comment]
I am also facing this issue -

Error - [error] <0.9511.7> handle.exe output did not contain a line beginning with '  File ', unable to determine used file descriptor count: "\r\nNthandle v4.22 - Handle viewe

**Comment by michaelklishin** [comment]
@Manvendra11 we don't have an environment that would reproduce this. `handle.exe` is a closed source piece of software and we don't know what exactly it may be doing. Out best best is developing an open source alternative but we can't promise that our team would eventually deliver this, or when that might happen.

Windows users are welcome to develop such a tool and then maybe we would introduce support for it in the free disk space monitoring parser.
