### ISSUE TITLE
Use cases for nowait

### ISSUE THREAD

**Issue by cressie176** [rabbitmq/discussions#189]
I'm digging into https://github.com/amqp-node/amqplib/issues/542, which highlights that amqplib does not support the `nowait` option for operations such as declaring queues and exchanges. I've confirmed the option is missing, but what I'm curious about is whether it is worth adding.

If I understand correctly, setting `nowait` to true will mean that RabbitMQ will not send a reply, so there is no point the client waiting for one. I expect this would result in slightly faster operations, but can't imagine a scenario where the difference is significant.

Is any one able to share scenarios I may be missing? 

Thank you

**Comment by michaelklishin** [comment]
Your understanding is correct. All scenarios I can think of involve high queue or binding churn and implicitly assume that the published data is not particularly important. It's very rare to see the `nowait` flag to be used intentionally.

**Comment by michaelklishin** [comment]
I will archive this repo as [rabbitmq/rabbitmq-server GitHub Discussions](https://github.com/rabbitmq/rabbitmq-server/discussions/) have been enabled for over a year now. This repository predates GitHub Discussions.
