### ISSUE TITLE
Delayed message exchange: configure delay units in seconds or milliseconds

### ISSUE THREAD

**Issue by liyiorg** [rabbitmq/discussions#25]
Hello,  Can delay units be calculated in seconds ？I want make the delay time range larger.

**Comment by michaelklishin** [comment]
Only one unit is supported. The upper bound is (2^32)-1 milliseconds, which is mentioned in the [Limitations section](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange#limitations).
