### ISSUE TITLE
Different versions create two queues with the same name

### ISSUE THREAD

**Issue by dudylan** [rabbitmq/discussions#33]
I use 5.4.1 java client to create a queue and 5.8 java client to create a queue. The result is two queues with the same name

**Comment by lukebakken** [comment]
It's not quite clear what the issue is. Could you provide code that I can compile and run?

**Comment by michaelklishin** [comment]
That's only possible if they are in the same virtual host or there are invisible characters in queue name (which RabbitMQ management UI will try to highlight in recent versions but not CLI tools). Please provide an executable way to reproduce.
