### ISSUE TITLE
blocking in connection.dispose method

### ISSUE THREAD

**Issue by Ivony** [rabbitmq/discussions#35]
somtimes, IConnection.Dispose method will blocking program very long time.

**Comment by michaelklishin** [comment]
I'm afraid we can only speculate with this much information. `IConnection#Close` is the way close a connection, not `IConnection#Dispose`. `IConnection#Abort` is a more aggressive way that ignores exceptions. Both should provide an override that allows you to specify a suitable timeout. As with heartbeat timeouts, we highly recommend against timeouts that are lower than 5 seconds.

There can be a broad number of reasons for a timeout, from a genuine connection interruption to a [resource alarm](https://www.rabbitmq.com/alarms.html) in effect that prevents target node from reading any data coming from clients unless the alarm clears.

**Comment by Ivony** [comment]
I found a manifestation, it's have to do with **Flow Control**.
when the connection state is **flow**, it's blocking and cannot Dispose or Abort.

Thank you very much.
