### ISSUE TITLE
Binding can't be deleted by api if it's routing key name contains special symbols (~, +)

### ISSUE THREAD

**Issue by anita-v** [rabbitmq/discussions#36]
1. Create binding from exchange1 to queue1 with routing key "name~".
2. Try to delete binding by api :
DELETE http://srv8-baljivac:15672/api/bindings/ns1/e/exchange1/q/queue1/name~
Status 404 Not Found
{
    "error": "Object Not Found",
    "reason": "Not Found"
}
replacing ~ with %7E doesn't work also

**Comment by michaelklishin** [comment]
`~` has a special meaning in HTTP API. Avoid those characters in routing keys or use safe derivative values such as hashes.

**Comment by michaelklishin** [comment]
`+` is a [reserved character](https://en.wikipedia.org/wiki/Percent-encoding#Types_of_URI_characters) in percent-encoding. This is not specific to RabbitMQ's HTTP API.
