### ISSUE TITLE
Can regular expressions be supported in routingKey ?

### ISSUE THREAD

**Issue by QiusHosens** [rabbitmq/discussions#48]
i want to use regular expressions in routingKey, such as a|b.
e.g, publish two types of messages(such as t1/t2) to an exchange.
i want to create three types of queue to bind this exchange.
1、receive message that type is t1;
2、receive message that type is t2;
3、receive message that type is t1 and t2.
how to solve this problem？
thanks

**Comment by michaelklishin** [comment]
@QiusHosens RabbitMQ core team would appreciate if no new questions were posted to the RabbitMQ server repository. GitHub is a tool our team uses for development, we do not use it as a support forum. If you cannot use the mailing list, at least use this dedicated repo. Thank you.
