### ISSUE TITLE
Support for SAC definitions in policy

### ISSUE THREAD

**Issue by pbillen** [rabbitmq/discussions#50]
Hi,

Are there plans to support the `single-active-consumer` flag of a queue in a policy? This does not seem to be possible in 3.8.2 (via admin UI or API). I cannot see a reason not to allow it to be defined in a policy, but maybe I am overlooking something? FWIW, I couldn't find anything related to this in https://github.com/rabbitmq/rabbitmq-server/pull/1802 and related issues.

**Comment by michaelklishin** [comment]
Policies are not supproted by features that are impossible to "undo" at runtime, e.g. priority queues use a different on disk layout, queue type is not something that can be changed for an existing queue, and so on.

@acogoluegnes @kjnilsson does SAC have similar aspects to it?

**Comment by michaelklishin** [comment]
There are no [policy definitions used](https://github.com/rabbitmq/rabbitmq-server/blob/master/test/single_active_consumer_SUITE.erl) in the test suite, so this increasingly looks like not a coincidence.

**Comment by acogoluegnes** [comment]
I think we discussed this topic already and came to the conclusion that it may not be such a good idea, as SAC is usually used when messages must be processed in the same order they arrive in the queue. Being able to disable SAC on some running queues could then be a disaster. This would also complicate the implementation.

This basically fits the definition of features that are impossible to "undo" at runtime.

I can add a note in the documentation about this.

**Comment by pbillen** [comment]
Right. I did not take into account that policies are strictly used for features which can be safely undone. I can see why SAC does not fall into that group.
Thank you for your feedback & documentation addition.
