### ISSUE TITLE
about consumer latency

### ISSUE THREAD

**Issue by didi20gh** [rabbitmq/discussions#51]
print msg :
id: test-030739-419, time: 420.052s, sent: 2102 msg/s, received: 10863 msg/s, min/median/75th/95th/99th consumer latency: 8141676/8715782/8769170/8826041/8833042 ?s
Q1 :
"?s" .  s for second or ms? :)

**Comment by michaelklishin** [comment]
`µs` is [microseconds](https://en.wikipedia.org/wiki/Microsecond).
