### ISSUE TITLE
Restart RAM node without disc node in RabbitMQ

### ISSUE THREAD

**Issue by yaboong** [rabbitmq/discussions#52]
In RabbitMQ document, [Restarting Cluster Nodes](https://www.rabbitmq.com/clustering.html#restarting), it says

> A stopping node picks an online cluster member (only disc nodes will be considered) to sync with after restart. Upon restart the node will try to contact that peer 10 times by default, with 30 second response timeouts. In case the peer becomes available in that time interval, the node successfully starts, syncs what it needs from the peer and keeps going. If the peer does not become available, the restarted node will give up and voluntarily stop.

I think it says **"You cannot stop and restart a RAM node if there are no available disk nodes in the cluster"**.

This is because restarting the RAM node requires one or more disk nodes to sync. If there are no disk nodes in the cluster, you cannot sync the RAM nodes, so it gives up and voluntarily stops. (That's what the document says)

But the result I tried was different from what the document says. Suppose that there are three nodes in the cluster. One disk node and two RAM nodes. Let's say each node is 'disk1', 'ram1' and 'ram2'.

I thought the process would look like this:

1. `stop ram1`
2. `stop disk1` -- at this point the cluster is RAM only cluster. ('ram2' node is the only node that's alive)
3. `start ram1` -- it should not be able to start because there're no disk nodes to sync.

But the result was different than I thought. **I was able to start the RAM node on the RAM only cluster without any disk nodes.**

Did I misunderstand something?

**Comment by michaelklishin** [comment]
I think one change that affects this (multiple years old) doc section is the addition of [sync operation retries]() so while this is a guess (no logs from any nodes were provided), it would [try N times](https://www.rabbitmq.com/clustering.html#resetting-nodes) periodically before giving up entirely.

**Comment by yaboong** [comment]
Thank you for letting me know that there is a Q&A group and sorry for posting a question here.

I didn't say that it was a safe operation scenario. I wanted to check if the document is correct.

When posting the same question to Google Groups, I'll also attach the logs.
