### ISSUE TITLE
Add Error Logging When Low on Storage

### ISSUE THREAD

**Issue by gchallen** [rabbitmq/discussions#54]
I recently ran into a very frustrating problem when using the [Bitnami RabbitMQ container](https://hub.docker.com/r/bitnami/rabbitmq/) as part of a multi-container service.

During testing using a set of containers started by Docker Compose, periodically everything would just completely hang. I eventually tracked this back to the RabbitMQ Java client hanging on a simple send operation. No problems were visible in the logs produced by the RabbitMQ container, despite the fact that log verbosity seemed reasonably high—client connections and disconnections were being logged, for example.

Obviously my title ruined the suspense, but the problem was that the RabbitMQ container was low on storage and Rabbit had decided to refuse to accept new messages. To add to the confusion, the queue was configured as not persistent, although of course I understand that Rabbit may need storage for other purposes during normal operation. To further add to the confusion, my machine is _not_ low on storage—but the Docker daemon was low given how much it had been configured to use. (The default Bitnami Docker container also needs a fair amount of storage: equal to the amount of RAM.)

Just to spare others some pain and confusion it would seem reasonable for RabbitMQ to log a warning when it refuses a message because storage is low. Perhaps it would also be good default behavior to actually fail here, rather than just hang. I mean, does RabbitMQ really expect storage to suddenly become available while waiting? Would it even complete the request in the very unlikely case that this did in fact happen?

Thanks for all of your hard work on this excellent service. Hopefully my suggestion above would just make RabbitMQ a bit more usable for the next newbie...

**Comment by michaelklishin** [comment]
We cannot comment on what might "hang" without a set of steps to reproduce. RabbitMQ relies on the standard filesystem and socket APIs that could exhibit such behavior. RabbitMQ cannot override them easily or at all.

We have had a [publicly available doc guide](https://www.rabbitmq.com/production-checklist.html#resource-limits-disk-space) for sanity checking production environments for a while.

**Comment by lukebakken** [comment]
RabbitMQ logs alarms and one such alarm is for disk space - https://www.rabbitmq.com/disk-alarms.html

If you did not see disk alarms in your log file there must be something unique to your environment. Like @michaelklishin said, there is little we can do without steps to reproduce an issue.
