### ISSUE TITLE
TLS certificate hot-reload

### ISSUE THREAD

**Issue by SergeAx** [rabbitmq/discussions#55]
Hello! I've built an installation of RabbitMQ alongside Certbot, so I can have SSL encryption for free, like any modern website. However, RabbitMQ as of version 3.7.23 (Docker Alpine image, ERLANG 22.2.4) is unable to refresh SSL certificate when it expires. Thus I need to auto-restart container every several days.

It would be nice to have the feature for (auto?)reloading SSL certificate from disk, without closing existing connections. Thank you!

**Comment by lukebakken** [comment]
Hello and thanks for using RabbitMQ.

Please take the time to search and see if your suggestion has been discussed. For instance, searching `rabbitmq-users` using the phrase `refresh ssl` turns up [this discussion](https://groups.google.com/forum/#!searchin/rabbitmq-users/refresh$20ssl%7Csort:date).

That discussion links to the following two:

* https://groups.google.com/forum/#!msg/rabbitmq-users/AdkDZhmYtAA/wI_etbl_BAAJ
* https://groups.google.com/forum/#!msg/rabbitmq-users/AdkDZhmYtAA/nTWjLisHBAAJ

@michaelklishin should have more to say about the possibility of adding a "TLS cert reload" feature.

**Comment by michaelklishin** [comment]
RabbitMQ does not implement TLS, Erlang does. In recent versions [1] there seems to be a way to trick the TLS implementation into reloading a certificate but it's not a part of the public API and not
something documented. [2] explains how to restart the TLS implementation. All connections would be dropped but certificate cache would also be cleared.

There is [3] which to some extent addresses the issue by overriding how the peer verification function that uses a periodically refreshed local or remote certificate source.

1. https://groups.google.com/forum/#!msg/rabbitmq-users/AdkDZhmYtAA/nTWjLisHBAAJ
2. https://stackoverflow.com/questions/51166713/rabbitmq-reload-refresh-new-certificates-without-restart
3. https://github.com/rabbitmq/rabbitmq-trust-store
