### ISSUE TITLE
No "Tracing" tab shown

### ISSUE THREAD

**Issue by AntonTrapp** [rabbitmq/discussions#57]
Hi!

Have a problem with this plugin.

> This plugin ships with RabbitMQ.
yes, shows in list
> Enabled it with rabbitmq-plugins enable
yes, get a nice log entry that it's enabled for the given vhost
> then see a "Tracing" tab in the management UI.
nope (except that it's hidden in white text on white ground, ...)

Plugin shows enabled in the plugin list.
Versions are: RabbitMQ 3.6.10 / Erlang 20.2.2
OS: Linux Mint (based on ubuntu 18.04.1)
Server logs: no errors/warnings, when enabling tracing it shows a text, that tracing has been enabled for the dev vhost.

Report (with trace related stuff):
`         rabbit_event,lists,queue,priority_queue,rabbit_router,rabbit_trace,
      {trace_vhosts,[<<"dev">>]},
amq.rabbitmq.trace	topic	true	false	true	[]	
amq.rabbitmq.trace	topic	true	false	true	[]	
`
Restarting rabbit (+ re-enabling tracing) does not change anything. Is this broken or is something missing in the documentation to get that tab?

**Comment by michaelklishin** [comment]
If the tab is not shown, it means the plugin hasn't been enabled. As Luke pointed out, RabbitMQ 3.6 has been out of support [for about 20 months now](https://www.rabbitmq.com/versions.html) and 3.6.10 specifically is [over two years old](https://www.rabbitmq.com/changelog.html). No much has changed for this plugin but there won't be much guidance for 3.6 at this point

**Comment by AntonTrapp** [comment]
Thanks @michaelklishin! Some times I forget how old the standard ubuntu LTS stuff is (and as only the minor version number changed I did not notice that),

If that is not an issue on current builds, just forget it, not worth any work :)

Thanks for your fast responding.

**Comment by lukebakken** [comment]
> If that is not an issue on current builds

It's not an issue that we know of in version 3.6, either.
