### ISSUE TITLE
RabbitMQ Consumer Count is high

### ISSUE THREAD

**Issue by bnbaliga** [rabbitmq/discussions#61]
We had upgraded the RabbitMQ Client in our C# Application to 5.1.2 from 4.x couple of months back. At times, we see that the consumer count shown in the RabbitMQ UI interface for a queue going from 2 to 200 (we have only 2 instances of the clients connected in reality) randomly at times. Has anyone seen this issue before? Do we need to upgrade the client to 6.x?

**Comment by michaelklishin** [comment]
You need to collect some data on what your applications do as with a very high degree of certaintly they leak consumers. There are three excellent options:

 * [Have solid monitoring](https://www.rabbitmq.com/monitoring.html) in place
 * Take a [traffic capture](https://www.rabbitmq.com/amqp-wireshark.html) to really truly find out what your applications do
 * Use [rabbitmq-event-exchange](https://github.com/rabbitmq/rabbitmq-event-exchange/) to track consumer registration and cancelation events

There isn't much else that our team can suggest with the amount of information provided.
