### ISSUE TITLE
Missing metrics

### ISSUE THREAD

**Issue by sosoriov** [rabbitmq/discussions#63]
Hi guys,

I'm using the new Prometheus integration for RabbitMq 3.8.0 and in general it works really well, but for some reason I don't have some of the metrics available like all Raft and Performance Test metrics. I checked the code and those metrics should be available:

https://github.com/rabbitmq/rabbitmq-prometheus/blob/master/src/collectors/prometheus_rabbitmq_core_metrics_collector.erl

Is there any settings that I'm missing?

I'm running RabbitMq 3.8.0

Thanks in advance.

**Comment by michaelklishin** [comment]
We cannot suggest anything with the amount of information provided. If your cluster does not use Raft-based features then there won't be any Raft metrics emitted. Please help others help you and provide some relevant information. Guessing is too expensive for our small team.

**Comment by lukebakken** [comment]
> Please help others help you and provide some relevant information

Via a message to the [public `rabbitmq-users` mailing list](https://groups.google.com/forum/#!forum/rabbitmq-users). Thanks.
