### ISSUE TITLE
RabbitMQ Docker fails to start after power loss

### ISSUE THREAD

**Issue by andi00** [rabbitmq/discussions#64]
Docker - rabbitmq:3.8.x-management

A power loss at service start can lead to a corrupt service which can't start anymore.
It looks like the root cause is the wal-File in the Folder /mnesia/'nodeId'/quorom/'nodeId'/ dictionary. 
If this file exist but is empty the service can't start.
If this file is missing or have a content there is no problem. 
Maybe a file check can be integrated.

Actually currently we don't use the quorom queues.
[log.zip](https://github.com/rabbitmq/rabbitmq-server/files/4229206/log.zip)

**Comment by michaelklishin** [comment]
Raft WAL will be used by other quorum-based features such as MQTT client ID tracking. There were changes around WAL recovery since `3.8.2`. The line from the log:

```
2020-02-13 13:26:45 =SUPERVISOR REPORT====
     Supervisor: {local,ra_log_wal_sup}
     Context:    start_error
     Reason:     {{case_clause,{ok,<<>>}},[{ra_log_wal,open_existing,1,[{file,"src/ra_log_wal.erl"},{line,646}]},{ra_log_wal,'-recover_wal/2-lc$^0/1-0-',1,[{file,"src/ra_log_wal.erl"},{line,265}]},{ra_log_wal,recover_wal,2,[{file,"src/ra_log_wal.erl"},{line,268}]},{ra_log_wal,init,1,[{file,"src/ra_log_wal.erl"},{line,214}]},{gen_batch_server,init_it,6,[{file,"src/gen_batch_server.erl"},{line,133}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
     Offender:   [{pid,undefined},{id,ra_log_wal},{mfargs,{ra_log_wal,start_link,[#{compute_checksums => true,dir => "/var/lib/rabbitmq/mnesia/rabbit@89a93f31077f/quorum/rabbit@89a93f31077f",max_size_bytes => 536870912,sync_method => datasync,write_strategy => default},[{max_batch_size,32768}]]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]
```

does not add up with the latest Ra release. Please provide a set of steps to reproduce (what does "power loss" mean exactly when it comes to a Docker container, for example?). In the meantime I will move this to the Raft library repo.

**Comment by andi00** [comment]
In our scenario we had a raspberry pi on which we had docker running.
The rabbit container restart policy was set to always so it will start automatically with docker.
On the rabbit mq server we currently use only the amqp Protocol with classic queues
At the startup of docker the power of the raspberry pi was cut off. At the next start of the raspberry pi and docker the rabbit container couldn't start.
After i created a new Container, i tried to reproduce the scenario and after 5 to 10 tries the container  couldn't be started again.
