### ISSUE TITLE
Limitation in RMQ federation

### ISSUE THREAD

**Issue by avarf** [rabbitmq/discussions#65]
Hi,
As I described [here](https://stackoverflow.com/questions/60338406/how-to-increase-the-rabbitmq-federation-rate) we are hitting a limitation in RMQ federation and no matter what I try I can't transfer more than 4-7k messages per second.

After some search, I found out that we are not the only one who is hitting this problem: https://www.reddit.com/r/rabbitmq/comments/5d5d2a/federation_bottlenecks_how_to_diagnose/

I want to know is this a real limitation in RMQ federation and how I can transfer more messages between two RMQs?

**Comment by lukebakken** [comment]
Hello and thanks for using RabbitMQ.

Unfortunately, you haven't provided any information for us to assist you. At minimum, we need the following:

* RabbitMQ and Erlang version
* Operating system version
* Operating environment (bare metal, AWS, GCP, etc)
* Network capacity between RabbitMQ nodes / clusters
* What you have tried. "No matter what I try" is not helpful. We need a script that contains the commands you are using to set up your federation link (or links). You can use the `rabbitmqctl` and `rabbitmqadmin` commands to automate this.
* How you are doing performance tests? Are you using [PerfTest](https://rabbitmq.github.io/rabbitmq-perf-test/stable/htmlsingle/)?

Without the above information we can't assist.

@Vanlightly has been doing some federation testing and could chime in.

Thanks

**Comment by avarf** [comment]
Hi, sorry for the lack of information.

I tested federation on different versions of RMQ, hardware and setups because I thought that I am doing something wrong. These are the answers to your questions:
- RabbitMQ and Erlang version
RMQ 3.7.12 - 3.8.1 and the erlang that comes with each RMQ image (for 3.8.1 it is 22.2)

- Operating system version
I only ran RMQ in a container but the host was always Ubuntu 18.04

- Operating environment (bare metal, AWS, GCP, etc)
bare metal. I ran it both on just two Ubuntu machines and also two nodes on bare metal on K8s 

Network capacity between RabbitMQ nodes / clusters
1 GB and the network is healthy since I don't see any problem and iperf3 doesn't show any problem too

- What you have tried. "No matter what I try" is not helpful. We need a script that contains the commands you are using to set up your federation link (or links). You can use the rabbitmqctl and rabbitmqadmin commands to automate this.
In the link that I put in my post and points to StackExchange I described what I already tried and I copy it here:
1. federation with different configs (with and without prefetch, ack, etc)
2. multiple exchanges in RMQ1 and create the same number of federations in RMQ2 and each federation point to one different exchange in RMQ1
3. federation to queues
4. Using the Consistent Hash Exchange (https://github.com/rabbitmq/rabbitmq-consistent-hash-exchange)
5. shovel (same message rate as federation)

- How you are doing performance tests? Are you using PerfTest?
I am using RMQ clients (python and go) to generate messages with different rates and receive them. No, I haven't used PerfTest.

**Comment by Vanlightly** [comment]
I was doing some testing on federation a couple of weeks ago on 3.8.2. I noticed federated exchange throughput was significantly lower than federated queue throughput. I will investigate further on Monday and see whats going on and reply here when I have answers.

**Comment by lukebakken** [comment]
@avarf 

> I only ran RMQ in a container 

We've seen enough network performance issues with RabbitMQ in docker or other containers that we can't accept performance numbers that use containers. If you can, repeat your tests without using containers. It's simple enough to run RabbitMQ using the `generic-unix` package or the packages that the RabbitMQ team provides.

**Comment by avarf** [comment]
Unfortunately running RMQ natively and without a container is not an option for me since our architecture is based on containerization and we must run everything in a container.

I don't think the limitation is related to the container networking since I am able to send and receive around 65k messages per second to a containerized RMQ. If there is anything wrong with the network I should see it with sending and receiving to a single RMQ container.

**Comment by lukebakken** [comment]
> If there is anything wrong with the network I should see it with sending and receiving to a single RMQ container.

Correct, you would. Thanks for confirming it's not that part of your environment.

**Comment by avarf** [comment]
Hi @Vanlightly do you have any update on this?

**Comment by Vanlightly** [comment]
@avarf I have done extensive benchmarking of federated exchanges, federated queues and shovels over the last week and I also see low federated exchange throughput. Specifically, low delivery rate from the upstream to the downstream (regardless of configuration).

So for single unit performance, a shovel may be the best choice. Shovels and federated exchanges both serve a similar goal: to move messages from A to B. While you get some extra automation with  federated exchanges, shovels show much more robust performance.

However, when comparing throughput of multiple exchanges/queues (10 and above) both ended up converging to the same throughput. That throughput was less than a single shovel. So shovels achieved much higher throughputs at low queue counts but the same at higher counts.

If back-pressure is attractive, prefer queue sourced shovels to federated exchanges and exchange sourced shovels. Non-rate limited publishers (using confirms) saw same throughput as the consumers on the downstream.

If back-pressure is not desired, then either an exchange sourced shovel or federated exchange may be the best choice, but remember single unit performance of the federated exchange is low.

**Comment by michaelklishin** [comment]
We have a hypothesis as to what may be the limiting factor for federation links. It is yet to be worked on, there is no ETA.

**Comment by michaelklishin** [comment]
There have been improvements starting with mid- to late-3.7.x releases where using a separate channel for command flow helped lower federation latency dramatically in some cases.

**Comment by avarf** [comment]
Hi @michaelklishin 
Are you sure about this? As I mentioned above my tests were running on RMQ 3.7.12 and 3.8.1 and your colleague also tested 3.8.2

**Comment by lukebakken** [comment]
@avarf 3.8.8 is the latest release. Please re-test with that version.

**Comment by michaelklishin** [comment]
@avarf I am sure that https://github.com/rabbitmq/rabbitmq-federation/pull/97 makes a massive difference for some workloads. It shipped in `3.7.26` and `3.8.3`.

**Comment by avarf** [comment]
Thank you for the clarification. Unfortunately at the moment, my team is busy working on some projects and I cannot run the tests again but any time I could run the tests I will inform you.
