### ISSUE TITLE
Problem !! expiration message queue

### ISSUE THREAD

**Issue by Thanakorn-ki** [rabbitmq/discussions#70]
## I found an issue about the expiration message queue.
For example, I had `notification.message` queue name with `dead-letter-exchange` to the exchange `exchange.sent.noti` binding `queue.sent.noti` . And then per message queue difference, the expiration assume published `message 1` with `expiration` is 60000 as a 1 min and I publish again `message 2` with `expiration` 10000 as a 10 ms go to `notification.message` queue.

## For the example above,
Expect `message 2` will be expiration and pop yourself go to `exchange.sent.noti` and that the exchange push to `queue.sent.noti` queue. But not as expected. It waits for `message 1` expired also pop `message 2`.

Do you recommend for use expiration?. Or we should create a queue by queue per expiration.

**Comment by michaelklishin** [comment]
I'm afraid I do not understand what you are asking. Consider putting together an executable example and starting a mailing list thread.
