### ISSUE TITLE
file_descriptors was conflict ，web vs rabbitmqctl command

### ISSUE THREAD

**Issue by spwangxp** [rabbitmq/discussions#77]
![Uploading image.png…](web manager)

![Uploading image.png…](rabbitmqctl command)

as the picture shows, the num of file_descriptors has a huge difference, which one was correct ?

**Comment by michaelklishin** [comment]
None of the images attached but Web UI is based on a periodically (every 5 seconds by default) updated stats database while CLI tools go "straight to the source". You can [reset stats](https://www.rabbitmq.com/management.html) to compare but it is a derived data source.

In addition, CLI tools will return nearly all metrics *for the node* while management UI's endpoints can perform aggregation.
