### ISSUE TITLE
Which version of PROXY PROTOCOL is compatible with RabbitMQ?

### ISSUE THREAD

**Issue by tiagosmx** [rabbitmq/discussions#83]
Proxy Protocol has two versions:
v1 with "human readable header format"
v2 with "binary header format"

I couldn't find which version of the protocol is supported by RabbitMQ in the documentation page:
https://www.rabbitmq.com/networking.html#proxy-protocol

Can someone shed light on this?

**Comment by lukebakken** [comment]
Thanks for using RabbitMQ.

The RabbitMQ team does not use GitHub for answering questions or discussions.

Would you mind asking this question on the [public mailing list](https://groups.google.com/forum/#!forum/rabbitmq-users) so that others can learn from it? We will update the docs as well.
