### ISSUE TITLE
One node has high memory in cluster

### ISSUE THREAD

**Issue by oyld** [rabbitmq/discussions#84]
I have a RabbitMQ cluster with 2 nodes. I'm create a fanout exchange and 100 queues. Node 1 has 50 queues and node 2 has 50 queues too. But the memory will become imbalance.

Here are some clues:
![image](https://user-images.githubusercontent.com/8790163/77919392-b3e2bf80-72cf-11ea-842d-9a74e3fc6e03.png)

![image](https://user-images.githubusercontent.com/8790163/77918893-17b8b880-72cf-11ea-92a1-3bf39c41996f.png)

![image](https://user-images.githubusercontent.com/8790163/77919182-6fefba80-72cf-11ea-983b-3522afddca9c.png)

![image](https://user-images.githubusercontent.com/8790163/77919239-7da54000-72cf-11ea-88d8-8dbbd9447077.png)

version is 3.7.17.

**Comment by michaelklishin** [comment]
This is mailing list material.

There are tools that [produce a memory usage breakdown](https://www.rabbitmq.com/memory-use.html). Use them as we cannot guess what uses the memory. One of the queues can have a massive backlog others do not have.

While not necessary related, it is worth mentioning that [two nodes clusters are strongly recommended against](https://www.rabbitmq.com/clustering.html#node-count).
