### ISSUE TITLE
Invalid argument, 'x-delayed-type' must be an existing exchange type

### ISSUE THREAD

**Issue by hualoqueros** [rabbitmq/discussions#86]
Hi, 
i dont know why this happen to me.. i've already download and enable this plugin. and this is list of plugin:
....
[  ] rabbitmq_consistent_hash_exchange 3.8.3
[E*] rabbitmq_delayed_message_exchange 3.8.0
....

is that version issues?  version 3.8.3 vs 3.8.0 ?

**Comment by lukebakken** [comment]
Please provide the following information:

* What operating system and version?
* RabbitMQ and Erlang version?
* How did you install the plugin? Please provide a complete set of steps.
* The _entire output_ of `rabbitmq-plugins list`, captured to a file, and attached to your response.

**Comment by hualoqueros** [comment]
Thanks @lukebakken for your response

1. Linux
2. RMQ version 3.8.3 Erlang 22.3
3. How to install: 
- download .**ez** https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/tag/v3.8.0
- move .ez file into /opt/rabbitmq/plugins
- `rabbitmq-plugins enable rabbitmq_delayed_message_exchange`
4.  this is list when `rabbitmq-plugin list`:
[  ] rabbitmq_amqp1_0                  3.8.3
[  ] rabbitmq_auth_backend_cache       3.8.3
[  ] rabbitmq_auth_backend_http        3.8.3
[  ] rabbitmq_auth_backend_ldap        3.8.3
[  ] rabbitmq_auth_backend_oauth2      3.8.3
[  ] rabbitmq_auth_mechanism_ssl       3.8.3
[  ] rabbitmq_consistent_hash_exchange 3.8.3
[E*] rabbitmq_delayed_message_exchange 3.8.0
[  ] rabbitmq_event_exchange           3.8.3
[  ] rabbitmq_federation               3.8.3
[  ] rabbitmq_federation_management    3.8.3
[  ] rabbitmq_jms_topic_exchange       3.8.3
[E*] rabbitmq_management               3.8.3
[e*] rabbitmq_management_agent         3.8.3
[  ] rabbitmq_mqtt                     3.8.3
[  ] rabbitmq_peer_discovery_aws       3.8.3
[  ] rabbitmq_peer_discovery_common    3.8.3
[  ] rabbitmq_peer_discovery_consul    3.8.3
[  ] rabbitmq_peer_discovery_etcd      3.8.3
[  ] rabbitmq_peer_discovery_k8s       3.8.3
[  ] rabbitmq_prometheus               3.8.3
[  ] rabbitmq_random_exchange          3.8.3
[  ] rabbitmq_recent_history_exchange  3.8.3
[  ] rabbitmq_sharding                 3.8.3
[  ] rabbitmq_shovel                   3.8.3
[  ] rabbitmq_shovel_management        3.8.3
[  ] rabbitmq_stomp                    3.8.3
[  ] rabbitmq_top                      3.8.3
[  ] rabbitmq_tracing                  3.8.3
[  ] rabbitmq_trust_store              3.8.3
[e*] rabbitmq_web_dispatch             3.8.3
[  ] rabbitmq_web_mqtt                 3.8.3
[  ] rabbitmq_web_mqtt_examples        3.8.3
[  ] rabbitmq_web_stomp                3.8.3
[  ] rabbitmq_web_stomp_examples       3.8.3

**Comment by hualoqueros** [comment]
Hi, i think, forgot input the argument key value pair.. so many thank @lukebakken
