### ISSUE TITLE
Chat not visible，Brower console error

### ISSUE THREAD

**Issue by shanzhaozhen** [rabbitmq/discussions#93]
Hello, my PC cann't see chat，Brower console error `Uncaught TypeError: $.plot is not a function` in charts.js
RabbitMQ version：rabbitmq-management-3.8.3
Running environment：docker 

![image](https://user-images.githubusercontent.com/29800728/79128121-946e8b00-7dd5-11ea-9110-7124dec56b8d.png)

**Comment by michaelklishin** [comment]
According to [this thread](https://stackoverflow.com/questions/29345524/flot-charts-giving-plot-is-not-a-function), one possible reason would be that the library did not, in fact, load. You can verify this hypothesis using browser developer tools (the Networking and Resources tabs or similar).
