### ISSUE TITLE
Channel closed due to partial tx completion on 3.8.3

### ISSUE THREAD

**Issue by ppogorzelski** [rabbitmq/discussions#95]
I got an IO excpetion when committing on an autorecovering channel:

> java.io.IOException: null
>         at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:116)
>         at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:112)
>         at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:134)
>         at com.rabbitmq.client.impl.ChannelN.txCommit(ChannelN.java:1318)
>         at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.txCommit(AutorecoveringChannel.java:503)
>         at com.ligertrading.nebula.common.rabbitmq.internal.TransactionalChannel.publish(TransactionalChannel.java:49)

This is a corresponding node entry:

> 2020-04-15 22:35:40.235 [error] <0.611.272> Error on AMQP connection <0.611.272> (127.0.0.1:37220 -> 127.0.0.1:5672, vhost: '/', user: 'nebula', state: running), channel 1:
>  operation basic.publish caused a connection exception channel_error: "unexpected command while processing 'tx.commit'"

It causes the channel to close and subsequent publishes throw AlreadyClosedException:

> com.rabbitmq.client.AlreadyClosedException: channel is already closed due to channel error; protocol method: #method<channel.close>(reply-code=406, reply-text=PRECONDITION_FAILED - partial tx completion, class-id=90, method-id=20)
>         at com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(AMQChannel.java:209)
>         at com.rabbitmq.client.impl.AMQChannel.transmit(AMQChannel.java:338)
>         at com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:686)
>         at com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:668)
>         at com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:658)
>         at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.basicPublish(AutorecoveringChannel.java:192)

The problem surfaced after a move from 3.5.6 to 3.8.3. It happens periodically (once every couple of M messages) on 3.8.3 nodes wheres 3.5.6 are just fine. Looks like some server error recovery changed in between and nodes are not able to handle this situation gracefully any longer.

**Comment by michaelklishin** [comment]
It's worth mentioning that

 * A [traffic capture](https://www.rabbitmq.com/amqp-wireshark.html) would reveal exactly what has been sent by the client
 * Synchronous channel operations in Java and most clients by default will wait for a response before returning. This is [true for tx.commit](https://github.com/rabbitmq/rabbitmq-java-client/blob/master/src/main/java/com/rabbitmq/client/impl/ChannelN.java#L1541) and we don't recall any changes in that area since the `3.5.x` days (so, in the last 5 years or so). Of course, we also don't know what client version was used then and now.
 * Transactions in AMQP 0-9-1 predominantly cover acks and are significantly less useful than most realize. [Publisher confirms](https://www.rabbitmq.com/confirms.html) help you accomplish the same thing without this limitation and the overhead, and with [several ways in which they can be used](https://www.rabbitmq.com/publishers.html#data-safety), including a completely asynchronous "streaming-style" approach

**Comment by ppogorzelski** [comment]
Thanks guys. Each channel is used by a single thread so this is not a concurrency issue. We don't really need high throughput messaging as we send batch of objects in every message (for other reasons), that's why we got transactions.

That's the client snippet. All access to the channel is synchronized and the code is really simple - basicPublish followed by txCommit.

`public synchronized void publish(Collection<T> objects, Map<String, Object> headers) throws IOException {
	BasicProperties properties = PERSISTENT_BASIC.builder().headers(headers).contentEncoding(encoding).build();
	byte[] payload = serialize(objects);

	channel.basicPublish(exchange, getRoutingKey(), properties, payload);
	channel.txCommit();
}`

This one went just fine:

> 22:42:47.563 [pool-1-thread-43] TRACE c.l.n.c.d.b.i.EventBroadcaster - Published ADDED event for 15 objects [Fill [...]]

Crashes here, I assume this is the moment when the channel gets closed:

> 22:42:48.073 [pool-1-thread-43] ERROR c.l.n.c.d.b.i.EventBroadcaster - Failed to publish ADDED event for 17 objects [Fill [...]]
> java.io.IOException: null
>         at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:116)
>         at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:112)
>         at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:134)
>         at com.rabbitmq.client.impl.ChannelN.txCommit(ChannelN.java:1318)
>         at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.txCommit(AutorecoveringChannel.java:503)
>         at com.xxx.common.rabbitmq.internal.TransactionalChannel.publish(TransactionalChannel.java:49)

Channel already closed:

> 22:42:48.341 [pool-1-thread-43] ERROR c.l.n.c.d.b.i.EventBroadcaster - Failed to publish ADDED event for 37 objects [Fill [...]]
> com.rabbitmq.client.AlreadyClosedException: channel is already closed due to channel error; protocol method: #method<channel.close>(reply-code=406, reply-text=PRECONDITION_FAILED - partial tx completion, class-id=90, method-id=20)
>         at com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(AMQChannel.java:209)
>         at com.rabbitmq.client.impl.AMQChannel.transmit(AMQChannel.java:338)
>         at com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:686)
>         at com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:668)
>         at com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:658)
>         at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.basicPublish(AutorecoveringChannel.java:192)
>         at com.xxx.nebula.common.rabbitmq.internal.TransactionalChannel.publish(TransactionalChannel.java:48)

From the logs above looks like the channel is closed the moment txCommit fails at the second publish so there's no way of rolling back the partially completed transaction.

**Comment by michaelklishin** [comment]
Do I understand it correctly that this code publishes one message and then immediately commits? Then you definitely should use publisher confirms as you are not getting anything out of transactions.

**Comment by michaelklishin** [comment]
Publisher confirms can be used in a number of ways which are covered in the [Publishers guide](https://www.rabbitmq.com/publishers.html#data-safety).

**Comment by ppogorzelski** [comment]
I can use publisher confirms or recover the channel by hand, not a problem. What I'm saying is that it looks like a bug as the code uses the channel in a synchronous manner and still getting partial tx completion error which results is na channel being closed. This is a legitimate API usage and we had no problems with it running 3.5.6 nodes.

**Comment by michaelklishin** [comment]
We will look into adding a test case that would reproduce. This particular way of using transactions is very much an edge case, and our team has plenty of other things to work on, so it is a bit hard to justify.
