### ISSUE TITLE
Port 15692 returning a 404 Not Found

### ISSUE THREAD

**Issue by thedraketaylor** [rabbitmq/discussions#96]
Hello,
I installed rabbitmq-server using the instuctions located at https://www.rabbitmq.com/install-debian.html (packagecloud install on Ubuntu 18.04 server if that matters). I then enabled the rabbitmq-prometheus plugin and got no errors. However, when I navigate to site:15692 I'm greeted with the following:
{"error":"Object Not Found","reason":"Not `Found"}

A quick look in the logs shows nothing amiss. Even going so far as showing:
Prometheus metrics: HTTP (non-TLS) listener started on port 15692

What can I do to get this working?

Thanks!

**Comment by michaelklishin** [comment]
Please use the mailing list for questions in the future.

The endpoint is [at `/metrics` by default](https://github.com/rabbitmq/rabbitmq-prometheus#configuration):

```
curl -v -H "Accept:text/plain;version=0.0.4" "http://localhost:15692/metrics"
```

**Comment by michaelklishin** [comment]
I updated Prometheus plugin README to make it clearer what the endpoint is. Its [doc guide](https://www.rabbitmq.com/prometheus.html) provides a Quick Start section that brings up a Grafana dashboard with a couple of make targets and already contains the same `curl` example.
