### ISSUE TITLE
test performance of mirror queue

### ISSUE THREAD

**Issue by jasonwangnanjing** [rabbitmq/discussions#97]
Hi Experts,
I want to test performance of mirror queue which defined within the cluster.But i did not find any suitable parameter from belog link.
https://rabbitmq.github.io/rabbitmq-perf-test/stable/htmlsingle/#introduction
May you know any possibility to do it? if not, could we require this as feature?

BR Jason

**Comment by acogoluegnes** [comment]
You can use the following parameters: `--queue-args x-queue-type=quorum --auto-delete false --flag persistent`. Note this will create a new quorum queue that will stay after the run (quorum queue cannot be auto-deleted). Using `--predeclared` to use a pre-defined queue is also a good solution.
