### ISSUE TITLE
单台 rabbitmq 并发 量大概是多少 ？

### ISSUE THREAD

**Issue by wang-dongfang** [rabbitmq/discussions#99]
单台 rabbitmq 并发 量大概是多少 ？求解

**Comment by michaelklishin** [comment]
It depens on how you define "concurrency". See [CPU Utilisation and Parallelism Considerations](https://www.rabbitmq.com/queues.html#runtime-characteristics) and the main [Runtime guide](https://www.rabbitmq.com/runtime.html).
